import {
  Award,
  BarChart3,
  Bot,
  Braces,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  Clock,
  Cloud,
  Code2,
  Compass,
  CreditCard,
  Database,
  Eye,
  FileText,
  Gauge,
  Globe,
  Handshake,
  Headphones,
  Heart,
  Infinity,
  Layers,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Lock,
  Mail,
  MessageSquare,
  Monitor,
  Palette,
  PenTool,
  Phone,
  PieChart,
  Rocket,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Target,
  Timer,
  TrendingUp,
  Upload,
  UserCheck,
  Users,
  Wrench,
  Zap,
} from "lucide-react";
import type { ComponentType, CSSProperties } from "react";

export type MarketingIcon = ComponentType<{ className?: string; style?: CSSProperties }>;

/**
 * Icon names are free text on CMS-editable content, so they are resolved at runtime.
 * A namespace import (`import * as Icons`) would defeat tree-shaking and pull the whole
 * lucide-react library into the eagerly-loaded landing chunk, so resolution goes through
 * this explicit registry instead.
 */
const ICONS: Record<string, MarketingIcon> = {
  Award,
  BarChart3,
  Bot,
  Braces,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  Clock,
  Cloud,
  Code2,
  Compass,
  CreditCard,
  Database,
  Eye,
  FileText,
  Gauge,
  Globe,
  Handshake,
  Headphones,
  Heart,
  Infinity,
  Layers,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Lock,
  Mail,
  MessageSquare,
  Monitor,
  Palette,
  PenTool,
  Phone,
  PieChart,
  Rocket,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Target,
  Timer,
  TrendingUp,
  Upload,
  UserCheck,
  Users,
  Wrench,
  Zap,
};

export function getIcon(name: string): MarketingIcon {
  return ICONS[name] || Sparkles;
}
