#!/usr/bin/env node
/**
 * The pre-flight check.
 *
 *   npm run check:content   — report, and rewrite CONTENT-NEEDED.md
 *   npm run check:launch    — the same, but exits non-zero if anything blocking
 *                             is still open. This is the gate in front of
 *                             switching the WordPress site off.
 *
 * It does four jobs:
 *
 *   1. Regenerates CONTENT-NEEDED.md from content/needed.json, so the document
 *      Sean is asked to work through cannot fall out of step with the questions
 *      the site is actually rendering.
 *   2. Refuses the copy the brief bans. "High quality" appeared five times on
 *      one page of the old site; it appears nowhere on this one, and the check
 *      is here so it stays that way after somebody else edits a file.
 *   3. Checks the colour pairs. Hi-vis on a concrete ground is 1.5:1 — the one
 *      contrast mistake this palette makes easy — so it is checked rather than
 *      remembered.
 *   4. Validates the MDX front matter that the site itself will reject at build
 *      time, but earlier and with a friendlier message.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const strict = process.argv.includes('--strict');

const problems = [];
const warnings = [];

/* ------------------------------------------------------------------ 1 ---- */

const needed = JSON.parse(fs.readFileSync(path.join(root, 'content/needed.json'), 'utf8'));

const order = [...needed].sort(
  (a, b) =>
    Number(b.blocksLaunch) - Number(a.blocksLaunch) ||
    a.priority - b.priority ||
    a.id.localeCompare(b.id),
);

const blocking = order.filter((n) => n.blocksLaunch);
const rest = order.filter((n) => !n.blocksLaunch);

function section(title, items, intro) {
  if (!items.length) return `## ${title}\n\nNothing outstanding.\n`;
  return [
    `## ${title}`,
    '',
    intro,
    '',
    ...items.flatMap((n) => [
      `### ${n.question}`,
      '',
      `**Why it matters.** ${n.why}`,
      '',
      `*Where the answer goes:* \`${n.where}\``,
      '',
    ]),
  ].join('\n');
}

const doc = `# What we still need from Sean

Generated by \`npm run check:content\` from \`content/needed.json\`. Do not edit this file by
hand — it will be overwritten. Change the questions in \`content/needed.json\`.

Every question below is showing on the website right now as a marked placeholder. Answer one,
delete its entry from \`content/needed.json\`, and the placeholder disappears from every page
that was using it.

**${blocking.length} of these block launch.** The current WordPress site should not be switched
off while any of them is open.

---

${section('Blocks launch', blocking, 'These have to be answered before the site goes live. Most of them are five-minute answers; the certificate and the photographs are the two that need someone to go and find a file.')}
---

${section('Wanted, but not blocking', rest, 'The site works without these. Each one makes it noticeably better at the job it is there to do.')}
---

## The quickest way through this

1. **Find the SafeContractor certificate.** It answers one blocking question and improves
   two pages. If it is a paper copy, a photograph of it is fine to start with.
2. **Ring the insurance broker** for the two limits and the renewal date. One call.
3. **Decide the email address** and check that mail on it is actually being read.
4. **Ten minutes on the phone** about the school hall, the Willaston shop and the factory
   job: roughly when, who for, how long, what went on, and whether the building stayed open.
5. **Photographs.** Off the phone, at full size, not saved down from Instagram.

Everything else can follow.
`;

fs.writeFileSync(path.join(root, 'CONTENT-NEEDED.md'), doc);

/* ------------------------------------------------------------------ 2 ---- */

/**
 * Phrases banned outright. Each of these is on the current site and each one
 * tells a commercial buyer they are reading a domestic decorator's website.
 */
const BANNED = [
  'high quality',
  'attention to detail',
  'with a smile',
  'your satisfaction is our reputation',
  'we pride ourselves',
  'second to none',
  'no job too small',
];

/**
 * Not banned, but rationed. "Painters and decorators" is a legitimate phrase on
 * the residential page, where the company genuinely does want that search. Used
 * more than once in a file it is keyword stuffing, which is what the old site
 * did in almost every sentence.
 */
const RATIONED = 'painters and decorators';

/**
 * The banned phrases are checked against what ships, not against what a comment
 * says about them. Several of the files below quote the old site's copy in order
 * to explain why it is not being repeated — and a check that cannot tell the
 * difference between using a phrase and naming it is a check people switch off.
 *
 * Block comments go entirely. Line comments go only when the `//` starts the
 * line, so a `https://` inside a string survives.
 */
function stripComments(text) {
  return text.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');
}

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (/\.(ts|tsx|mdx|json)$/.test(entry.name)) out.push(full);
  }
  return out;
}

const contentFiles = walk(path.join(root, 'content'));

for (const file of contentFiles) {
  const rel = path.relative(root, file);
  const text = stripComments(fs.readFileSync(file, 'utf8'));
  const lower = text.toLowerCase();

  for (const phrase of BANNED) {
    // scripts/check-content.mjs lists the phrases itself; content must not.
    if (lower.includes(phrase)) {
      problems.push(`${rel}: contains banned phrase "${phrase}" (see NO TEMPLATE PATTERNS)`);
    }
  }

  const uses = lower.split(RATIONED).length - 1;
  if (uses > 1) {
    problems.push(
      `${rel}: "${RATIONED}" appears ${uses} times. Once is positioning, twice is keyword stuffing.`,
    );
  }
}

/* ------------------------------------------------------------------ 3 ---- */

const TOKENS = {
  navy: '#0E1A29',
  slate: '#17293E',
  paper: '#FFFFFF',
  mist: '#F1F4F7',
  amber: '#E0A020',
  rule: '#D7DEE5',
  ruleDark: '#2B4159',
  text: '#33455C',
  label: '#5A6E86',
  muted: '#A7B8CC',
};

function luminance(hex) {
  const [r, g, b] = [1, 3, 5].map((i) => {
    const c = parseInt(hex.slice(i, i + 2), 16) / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function contrast(a, b) {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

/** Every foreground/background pair the site actually uses. */
const PAIRS = [
  ['navy', 'paper', 4.5, 'headings on the primary ground'],
  ['text', 'paper', 4.5, 'body copy on the primary ground'],
  ['label', 'paper', 4.5, 'label type on the primary ground'],
  ['navy', 'mist', 4.5, 'headings on the secondary light band'],
  ['text', 'mist', 4.5, 'body copy on the secondary light band'],
  ['label', 'mist', 4.5, 'label type on the secondary light band'],
  ['paper', 'navy', 4.5, 'type on the dark bands'],
  ['muted', 'navy', 4.5, 'secondary copy on the dark bands'],
  ['muted', 'slate', 4.5, 'secondary copy on raised dark blocks'],
  ['amber', 'navy', 4.5, 'the accent as type, on dark only'],
  ['navy', 'amber', 4.5, 'the label inside the primary action'],
];

for (const [fg, bg, min, what] of PAIRS) {
  const ratio = contrast(TOKENS[fg], TOKENS[bg]);
  if (ratio < min) {
    problems.push(
      `contrast: ${fg} on ${bg} is ${ratio.toFixed(2)}:1, below ${min}:1 — ${what}`,
    );
  }
}

/**
 * The one mistake this palette makes easy.
 *
 * Amber is 2.3:1 on white. It is a fill and a rule on light grounds — a block
 * with navy type on it, or a 3px marking — and it is never a word. On the dark
 * bands it is 7.9:1 and may be type. The `--mark` variable resolves to the right
 * one per ground so a component never has to remember; this checks that nobody
 * has reached past it and hardcoded the amber.
 */
const amberOnPaper = contrast(TOKENS.amber, TOKENS.paper);
if (amberOnPaper >= 4.5) {
  warnings.push(
    'contrast: amber now passes on white — the palette has changed and the "fills only, never type" rule in globals.css should be revisited.',
  );
}

for (const file of walk(path.join(root, 'src'))) {
  const text = fs.readFileSync(file, 'utf8');
  if (/data-ground=["'](paper|mist)["'][\s\S]{0,400}?(text-\[var\(--color-amber\)\]|text-amber|text-hivis)/.test(text)) {
    problems.push(
      `${path.relative(root, file)}: amber type on a light ground — ${amberOnPaper.toFixed(2)}:1. Use var(--mark), which is navy there.`,
    );
  }
}

/* ------------------------------------------------------------------ 4 ---- */

const projectsDir = path.join(root, 'content/projects');
for (const file of fs.readdirSync(projectsDir).filter((f) => f.endsWith('.mdx') && !f.startsWith('_'))) {
  const { data } = matter(fs.readFileSync(path.join(projectsDir, file), 'utf8'));
  const rel = `content/projects/${file}`;
  const image = data.image ?? {};

  if (image.src && !image.alt) problems.push(`${rel}: photograph has no alt text.`);
  if (image.src && (!image.width || !image.height)) {
    problems.push(`${rel}: photograph has no width/height — the page will jump as it loads.`);
  }
  if (!image.src && !image.needs) {
    problems.push(`${rel}: empty photograph slot with no brief saying what belongs there.`);
  }
  if (data.status === 'drafted') {
    const open = ['clientType', 'scope', 'location', 'duration', 'system', 'occupied', 'year']
      .filter((k) => data[k] === null || data[k] === undefined);
    if (open.length) {
      warnings.push(`${rel}: ${open.length} caption fields outstanding (${open.join(', ')}).`);
    }
  }
}

const sectorsDir = path.join(root, 'content/sectors');
const indexed = fs
  .readFileSync(path.join(root, 'content/sectors.ts'), 'utf8')
  .matchAll(/slug: '([^']+)'/g);
for (const [, slug] of indexed) {
  if (!fs.existsSync(path.join(sectorsDir, `${slug}.mdx`))) {
    problems.push(`content/sectors/${slug}.mdx is missing but is in the sector index.`);
  }
}

/* ---------------------------------------------------------------- report -- */

const line = '─'.repeat(64);
console.log(line);
console.log('McDonald Painting Contractors — content check');
console.log(line);

console.log(`\nOutstanding questions: ${needed.length} (${blocking.length} block launch)`);
console.log('CONTENT-NEEDED.md rewritten.\n');

if (warnings.length) {
  console.log('Notes:');
  for (const w of warnings) console.log(`  · ${w}`);
  console.log();
}

if (problems.length) {
  console.log('Problems:');
  for (const p of problems) console.log(`  ✗ ${p}`);
  console.log();
  process.exit(1);
}

console.log('No problems found.');

if (strict && blocking.length) {
  console.log(
    `\n✗ Not ready to launch: ${blocking.length} blocking question${
      blocking.length === 1 ? '' : 's'
    } still open. See CONTENT-NEEDED.md.`,
  );
  process.exit(1);
}

if (strict) console.log('\n✓ Ready to launch.');
