#!/usr/bin/env node
/**
 * The launch gate.
 *
 *   npm run check:content   report what is outstanding, and rewrite CONTENT-NEEDED.md
 *   npm run check:launch    the same, but exits non-zero if anything blocking is open
 *
 * Run check:launch before the site is pointed at a domain. It is the difference
 * between "the site is finished" and "the site is finished and nobody has
 * published a phone number that has not been dialled, a rating nobody has
 * looked at, or a review with no words in it".
 *
 * Every flag below is read out of the source rather than tracked separately, so
 * this script cannot drift from what actually ships.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const strict = process.argv.includes('--strict')

const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8')
const needed = JSON.parse(read('content/needed.json'))

const site = read('content/site.ts')
const reviews = read('content/reviews.ts')
const areas = read('content/areas.ts')
const photos = read('content/photos.ts')

/* ----------------------------------------------------------------- flags --- */
/* Keyed by the id in needed.json. `on` means the question has been answered
   and the answer is in the code. */

const flags = {
  phone: {
    on: /const PHONE_CONFIRMED = true/.test(site),
    file: 'content/site.ts',
  },
  'yell-listing': {
    on: /yellListingConfirmed = true/.test(site),
    file: 'content/site.ts',
  },
  'rating-figure': {
    on: /seenOnListing: true/.test(reviews),
    file: 'content/reviews.ts',
  },
  'review-excerpts': {
    on: !/excerpt: null/.test(reviews),
    file: 'content/reviews.ts',
  },
  'service-towns': {
    on: /confirmed: true/.test(areas),
    file: 'content/areas.ts',
  },
  domain: {
    on: /DOMAIN_REGISTERED = true/.test(site),
    file: 'content/site.ts',
  },
  'insurance-cscs': {
    on: /confirmed: true/.test(site),
    file: 'content/site.ts',
  },
  'google-profile': {
    on: !/googleProfileUrl: string \| null = null/.test(site),
    file: 'content/site.ts',
  },
  'working-hours': {
    on: !/export const openingHours: null = null/.test(site),
    file: 'content/site.ts',
  },
  photographs: {
    on: /src:/.test(photos),
    file: 'content/photos.ts',
  },
  email: {
    on: !/export const email: string \| null = null/.test(site),
    file: 'content/site.ts',
  },
}

/* Not a content question — an environment one. The form hides itself until one
   of these is set, so this is reported rather than gating anything. */
const deliveryConfigured = Boolean(
  process.env.ENQUIRY_WEBHOOK_URL ||
    (process.env.RESEND_API_KEY && process.env.ENQUIRY_TO),
)

/* --------------------------------------------------------------- report --- */

const open = needed
  .map((item) => ({ ...item, ...(flags[item.id] ?? { on: false, file: item.where }) }))
  .filter((item) => !item.on)
  .sort((a, b) => a.priority - b.priority || a.id.localeCompare(b.id))

const answered = needed.filter((item) => flags[item.id]?.on)
const blocking = open.filter((item) => item.blocksLaunch)

const line = (s = '') => process.stdout.write(`${s}\n`)

line()
line('A Edwards Decorating — outstanding content')
line('='.repeat(42))
line()

if (answered.length > 0) {
  line(`Answered: ${answered.map((a) => a.id).join(', ')}`)
  line('(delete those entries from content/needed.json)')
  line()
}

if (open.length === 0) {
  line('Nothing outstanding.')
} else {
  for (const item of open) {
    line(`${item.blocksLaunch ? '[BLOCKS LAUNCH]' : '[wanted]      '} ${item.id}`)
    line(`  ask:   ${item.question}`)
    line(`  why:   ${item.why}`)
    line(`  where: ${item.where}`)
    line()
  }
}

line(
  `Enquiry delivery: ${deliveryConfigured ? 'configured' : 'not configured — the form is hidden and the contact field shows the phone number'}`,
)
line()

/* ------------------------------------------------- regenerate the markdown --- */

const md = [
  '# Content needed — A Edwards Decorating',
  '',
  '**Generated by `npm run check:content`. Do not edit by hand** — edit',
  '`content/needed.json` and run it again.',
  '',
  'This is one phone call. Andy has no website, so almost nothing about him is',
  'confirmed in writing anywhere; everything below is either a fact the site',
  'refuses to invent or a fact it refuses to print until somebody has checked it.',
  '',
  'Anything marked **blocks launch** means the site should not be pointed at a',
  'domain while it is still open.',
  '',
  '---',
  '',
]

for (const item of open) {
  md.push(`## ${item.id}${item.blocksLaunch ? ' — **blocks launch**' : ''}`)
  md.push('')
  md.push(`**Ask:** ${item.question}`)
  md.push('')
  md.push(`**Why:** ${item.why}`)
  md.push('')
  md.push(`**Answer goes in:** \`${item.where}\``)
  md.push('')
}

if (open.length === 0) {
  md.push('Nothing outstanding.', '')
}

md.push('---', '')
md.push('## Not a question for Andy', '')
md.push(
  '- **Enquiry delivery.** Set `ENQUIRY_WEBHOOK_URL`, or `RESEND_API_KEY` plus',
  '  `ENQUIRY_TO`, in the host\'s environment. Until one of them is set the form',
  '  does not render at all and the contact field shows his phone number instead.',
  '  Currently: ' + (deliveryConfigured ? 'configured.' : '**not configured**.'),
  '',
)

fs.writeFileSync(path.join(root, 'CONTENT-NEEDED.md'), md.join('\n'))
line('CONTENT-NEEDED.md rewritten.')
line()

if (strict && blocking.length > 0) {
  line(`${blocking.length} blocking question${blocking.length === 1 ? '' : 's'} still open:`)
  for (const item of blocking) line(`  - ${item.id}`)
  line()
  process.exit(1)
}
