#!/usr/bin/env node
/**
 * Builds the drop-on-any-host bundle.
 *
 *   npm run pack
 *
 * Runs the static export, writes the host configuration files from
 * hosting/headers.mjs so the security headers survive on a host that is not a
 * Node server, drops HOSTING.md in beside them, and zips the lot.
 *
 * Output: aedwards-decorating-site.zip in this directory.
 */

import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  IMMUTABLE_CACHE,
  IMMUTABLE_PATH,
  SECURITY_HEADERS,
} from '../hosting/headers.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const out = path.join(root, 'out')
const zip = path.join(root, 'aedwards-decorating-site.zip')

const say = (s) => process.stdout.write(`${s}\n`)

/*
 * Next exports the share card to a path with no file extension, and the HTML
 * references it that way. Hosts guess the content type from the extension, so
 * without this it goes out as application/octet-stream and Facebook, WhatsApp
 * and LinkedIn all decline to render it — the card silently does not work,
 * which is exactly the kind of thing nobody notices for a year.
 */
const OG_IMAGE_PATH = '/opengraph-image'
const OG_IMAGE_NOTE = [
  'The share card is exported without a file extension, so it needs its',
  'content type stating outright or social networks will not render it.',
]

/* ------------------------------------------------------------------ build --- */

say('Building the static export…')
fs.rmSync(out, { recursive: true, force: true })
fs.rmSync(path.join(root, '.next'), { recursive: true, force: true })
execFileSync('npx', ['next', 'build'], {
  cwd: root,
  stdio: 'inherit',
  env: { ...process.env, STATIC_EXPORT: '1' },
})

if (!fs.existsSync(path.join(out, 'index.html'))) {
  throw new Error('The export produced no index.html. Something went wrong above.')
}

/* ------------------------------------------------------- host config files --- */

/* Netlify and Cloudflare Pages. */
const netlify = [
  '# Generated by npm run pack — edit hosting/headers.mjs, not this file.',
  '',
  '/*',
  ...SECURITY_HEADERS.map((h) => `  ${h.key}: ${h.value}`),
  '',
  `${IMMUTABLE_PATH}*`,
  `  Cache-Control: ${IMMUTABLE_CACHE}`,
  '',
  ...OG_IMAGE_NOTE.map((l) => `# ${l}`),
  OG_IMAGE_PATH,
  '  Content-Type: image/png',
  '',
].join('\n')
fs.writeFileSync(path.join(out, '_headers'), netlify)

/* Apache, which is what most cPanel shared hosting still runs. */
const apache = [
  '# Generated by npm run pack — edit hosting/headers.mjs, not this file.',
  '',
  '<IfModule mod_headers.c>',
  ...SECURITY_HEADERS.map((h) => `  Header always set ${h.key} "${h.value.replace(/"/g, '\\"')}"`),
  '</IfModule>',
  '',
  '# Most hosts compress by default, but not all of them, and uncompressed HTML',
  '# and JavaScript over a phone connection is the single biggest thing that',
  '# slows this site down: measured, it is the difference between a Lighthouse',
  '# mobile score of 86 and one of 98.',
  '<IfModule mod_deflate.c>',
  '  AddOutputFilterByType DEFLATE text/html text/css text/plain text/xml',
  '  AddOutputFilterByType DEFLATE application/javascript text/javascript',
  '  AddOutputFilterByType DEFLATE application/json image/svg+xml',
  '</IfModule>',
  '',
  '# The build output is content-hashed, so it can be cached forever.',
  '<IfModule mod_headers.c>',
  '  <FilesMatch "\\.(js|css|woff2|svg|png|avif|webp)$">',
  `    Header set Cache-Control "${IMMUTABLE_CACHE}"`,
  '  </FilesMatch>',
  '</IfModule>',
  '',
  ...OG_IMAGE_NOTE.map((l) => `# ${l}`),
  `<Files "${OG_IMAGE_PATH.replace(/^\//, '')}">`,
  '  ForceType image/png',
  '</Files>',
  '',
  'ErrorDocument 404 /404.html',
  '',
  '# Serve pretty URLs if the host has not already.',
  '<IfModule mod_rewrite.c>',
  '  RewriteEngine On',
  '  RewriteCond %{REQUEST_FILENAME} !-f',
  '  RewriteCond %{REQUEST_FILENAME} !-d',
  '  RewriteCond %{REQUEST_FILENAME}/index.html -f',
  '  RewriteRule ^(.*)$ /$1/index.html [L]',
  '</IfModule>',
  '',
].join('\n')
fs.writeFileSync(path.join(out, '.htaccess'), apache)

fs.copyFileSync(path.join(root, 'hosting', 'HOSTING.md'), path.join(out, 'HOSTING.md'))

say('Wrote _headers, .htaccess and HOSTING.md.')

/* -------------------------------------------------------------------- zip --- */

fs.rmSync(zip, { force: true })
// -r recurse, -q quiet, and the trailing . so dotfiles (.htaccess) go in too.
execFileSync('zip', ['-r', '-q', zip, '.'], { cwd: out, stdio: 'inherit' })

const mb = (fs.statSync(zip).size / 1024 / 1024).toFixed(2)
say('')
say(`${path.relative(root, zip)} — ${mb} MB`)
say('Unzip it into the web root. Read HOSTING.md inside it first.')
