import { EditorElement, Breakpoint, StyleMap } from './types.ts';

/** Convert camelCase to kebab-case */
function toKebab(str: string): string {
  return str.replace(/([A-Z])/g, '-$1').toLowerCase();
}

/** Convert a StyleMap object to a CSS string */
export function stylesToCSS(styles: StyleMap): string {
  return Object.entries(styles)
    .filter(([, v]) => v !== undefined && v !== '')
    .map(([k, v]) => `  ${toKebab(k)}: ${v};`)
    .join('\n');
}

/** Get resolved styles for a breakpoint (cascading) */
export function getResolvedStyles(el: EditorElement, bp: Breakpoint): StyleMap {
  const base = (el.styles || {}).desktop ?? {};
  if (bp === 'desktop') return base;
  const override = bp === 'tablet' ? (el.styles || {}).tablet : (el.styles || {}).mobile;
  return { ...base, ...override };
}

/** Generate a semantic CSS class name */
/**
 * The class name an element carries into exported and published code.
 *
 * This is the single most visible thing about generated code. Names like
 * "h1-h1" and "nav-nav1" are a machine stamp, and they were the reason the
 * export read as generated rather than written by somebody.
 *
 * So: if you named the element, that name IS the class - `.hero-banner`,
 * no suffix, no id fragment. Two elements sharing a name deliberately share
 * a class, which is how a class is supposed to work and how Webflow treats
 * them. Only unnamed elements get a short stable suffix, and only because
 * they have nothing else to be called.
 */
export function generateClassName(el: EditorElement): string {
  const semanticMap: Record<string, string> = {
    section: 'section', container: 'container', columns: 'columns', grid: 'grid',
    heading: ((el.props || {}).level as string) || 'heading', text: 'text', button: 'button',
    image: 'image', video: 'video', navbar: 'navbar', footer: 'footer',
    link: 'link', form: 'form', input: 'input', textarea: 'textarea',
    select: 'select', checkbox: 'checkbox', radio: 'radio', card: 'card',
    spacer: 'spacer', divider: 'divider', list: 'list', quote: 'quote',
  };

  const authored = el.name
    ?.trim()
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();

  // A name the author chose is the whole class. Nothing appended.
  if (authored) return authored;

  const base = semanticMap[el.type] || el.type.replace(/[^a-z0-9-]/gi, '-').toLowerCase();
  // Unnamed elements still need to be distinguishable. Four base-36
  // characters off a hash of the id: stable across builds, short enough to
  // read past.
  let h = 0;
  for (let i = 0; i < el.id.length; i++) h = (h * 31 + el.id.charCodeAt(i)) >>> 0;
  return `${base}-${h.toString(36).slice(0, 4)}`;
}

/** CSS Reset + Base — Production-grade */
const CSS_RESET = `/* ═══════════════════════════════════════════
   Generated by Quooro Workshop
   Production-Ready Stylesheet
   ═══════════════════════════════════════════ */

/* Reset */
*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  -webkit-text-size-adjust: 100%;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility;
  scroll-behavior: smooth;
  font-size: 16px;
}

body {
  font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  line-height: 1.6;
  color: #1a1a1a;
  background-color: #ffffff;
  min-height: 100vh;
  overflow-x: hidden;
}

img, video, svg { max-width: 100%; height: auto; display: block; }
a { color: inherit; text-decoration: none; }
button { cursor: pointer; border: none; background: none; font: inherit; color: inherit; }
input, textarea, select { font: inherit; color: inherit; }
ul, ol { list-style: none; }
h1, h2, h3, h4, h5, h6 { font-weight: 700; line-height: 1.2; }

/* Utilities */
.sr-only {
  position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px;
  overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;
}

/* Scroll Animations */
[data-animate] {
  opacity: 0;
  transform: translateY(20px);
  transition: opacity 0.6s ease, transform 0.6s ease;
}
[data-animate].is-visible {
  opacity: 1;
  transform: translateY(0);
}

/* Responsive Images */
img { object-fit: cover; }

/* Focus Styles */
:focus-visible {
  outline: 2px solid #0073E6;
  outline-offset: 2px;
}

/* Selection */
::selection {
  background: rgba(0, 115, 230, 0.2);
  color: inherit;
}

`;

/** Merge duplicate media queries for cleaner output */
function mergeMediaQueries(rules: string[]): string[] {
  const desktop: string[] = [];
  const tabletRules: string[] = [];
  const mobileRules: string[] = [];

  for (const rule of rules) {
    if (rule.startsWith('@media (max-width: 768px)')) {
      // Extract inner content
      const inner = rule.replace('@media (max-width: 768px) {\n', '').replace(/\n}$/, '');
      tabletRules.push(inner);
    } else if (rule.startsWith('@media (max-width: 480px)')) {
      const inner = rule.replace('@media (max-width: 480px) {\n', '').replace(/\n}$/, '');
      mobileRules.push(inner);
    } else {
      desktop.push(rule);
    }
  }

  const result = [...desktop];
  if (tabletRules.length) {
    result.push(`/* ── Tablet ───────────────────────────────── */\n@media (max-width: 768px) {\n${tabletRules.join('\n\n')}\n}`);
  }
  if (mobileRules.length) {
    result.push(`/* ── Mobile ───────────────────────────────── */\n@media (max-width: 480px) {\n${mobileRules.join('\n\n')}\n}`);
  }
  return result;
}

/** Build full CSS for an element tree */
export function buildCSS(elements: EditorElement[]): string {
  const desktopRules: string[] = [];
  const tabletRules: string[] = [];
  const mobileRules: string[] = [];
  const keyframeRules: string[] = [];

  function walk(el: EditorElement) {
    const cls = generateClassName(el);

    // Desktop
    const desktopCSS = stylesToCSS((el.styles || {}).desktop ?? {});
    if (desktopCSS) desktopRules.push(`.${cls} {\n${desktopCSS}\n}`);

    // Hover
    if (el.hoverStyles) {
      const hover = stylesToCSS(el.hoverStyles);
      if (hover) desktopRules.push(`.${cls}:hover {\n  transition: all 0.3s ease;\n${hover}\n}`);
    }

    // Tablet
    if ((el.styles || {}).tablet) {
      const tabletCSS = stylesToCSS((el.styles || {}).tablet);
      if (tabletCSS) tabletRules.push(`  .${cls} {\n  ${tabletCSS}\n  }`);
    }

    // Mobile
    if ((el.styles || {}).mobile) {
      const mobileCSS = stylesToCSS((el.styles || {}).mobile);
      if (mobileCSS) mobileRules.push(`  .${cls} {\n  ${mobileCSS}\n  }`);
    }

    // Animations
    if (el.animations && el.animations.type !== 'none') {
      const anim = el.animations;
      const keyframeName = `anim-${anim.type}`;
      const keyframes = getKeyframes(anim.type);
      if (keyframes) {
        // Only add keyframes once per animation type
        const kfRule = `@keyframes ${keyframeName} {\n${keyframes}\n}`;
        if (!keyframeRules.includes(kfRule)) keyframeRules.push(kfRule);
        desktopRules.push(`.${cls} {\n  animation: ${keyframeName} ${anim.duration || 0.6}s ${anim.easing || 'ease'} ${anim.delay || 0}s both;\n}`);
      }
    }

    (el.children || []).forEach(walk);
  }

  elements.forEach(walk);

  // Assemble output: Reset → Keyframes → Desktop → Tablet → Mobile
  const sections = [CSS_RESET];

  if (keyframeRules.length) {
    sections.push(`/* ── Animations ──────────────────────────── */\n${keyframeRules.join('\n\n')}`);
  }

  sections.push(`/* ── Components ──────────────────────────── */\n${desktopRules.join('\n\n')}`);

  if (tabletRules.length) {
    sections.push(`/* ── Tablet (≤768px) ─────────────────────── */\n@media (max-width: 768px) {\n${tabletRules.join('\n\n')}\n}`);
  }

  if (mobileRules.length) {
    sections.push(`/* ── Mobile (≤480px) ─────────────────────── */\n@media (max-width: 480px) {\n${mobileRules.join('\n\n')}\n}`);
  }

  return sections.join('\n\n');
}

function getKeyframes(type: string): string | null {
  switch (type) {
    case 'fadeIn': return '  from { opacity: 0; }\n  to { opacity: 1; }';
    case 'fadeInUp': return '  from { opacity: 0; transform: translateY(20px); }\n  to { opacity: 1; transform: translateY(0); }';
    case 'fadeInDown': return '  from { opacity: 0; transform: translateY(-20px); }\n  to { opacity: 1; transform: translateY(0); }';
    case 'fadeInLeft': return '  from { opacity: 0; transform: translateX(-20px); }\n  to { opacity: 1; transform: translateX(0); }';
    case 'fadeInRight': return '  from { opacity: 0; transform: translateX(20px); }\n  to { opacity: 1; transform: translateX(0); }';
    case 'slideUp': return '  from { opacity: 0; transform: translateY(30px); }\n  to { opacity: 1; transform: translateY(0); }';
    case 'slideDown': return '  from { opacity: 0; transform: translateY(-30px); }\n  to { opacity: 1; transform: translateY(0); }';
    case 'slideLeft': return '  from { opacity: 0; transform: translateX(30px); }\n  to { opacity: 1; transform: translateX(0); }';
    case 'slideRight': return '  from { opacity: 0; transform: translateX(-30px); }\n  to { opacity: 1; transform: translateX(0); }';
    case 'scaleIn': return '  from { opacity: 0; transform: scale(0.9); }\n  to { opacity: 1; transform: scale(1); }';
    case 'scaleUp': return '  from { opacity: 0; transform: scale(0.5); }\n  to { opacity: 1; transform: scale(1); }';
    case 'scaleDown': return '  from { opacity: 0; transform: scale(1.2); }\n  to { opacity: 1; transform: scale(1); }';
    case 'bounceIn': return '  0% { opacity: 0; transform: scale(0.3); }\n  50% { transform: scale(1.05); }\n  70% { transform: scale(0.9); }\n  100% { opacity: 1; transform: scale(1); }';
    case 'elastic': return '  0% { opacity: 0; transform: scale(0); }\n  55% { transform: scale(1.1); }\n  75% { transform: scale(0.95); }\n  100% { opacity: 1; transform: scale(1); }';
    case 'rotateIn': return '  from { opacity: 0; transform: rotate(-90deg); }\n  to { opacity: 1; transform: rotate(0); }';
    case 'flipInX': return '  from { opacity: 0; transform: perspective(400px) rotateX(90deg); }\n  to { opacity: 1; transform: perspective(400px) rotateX(0); }';
    case 'flipInY': return '  from { opacity: 0; transform: perspective(400px) rotateY(90deg); }\n  to { opacity: 1; transform: perspective(400px) rotateY(0); }';
    case 'blurIn': return '  from { opacity: 0; filter: blur(12px); }\n  to { opacity: 1; filter: blur(0); }';
    case 'pulse': return '  0%, 100% { opacity: 1; }\n  50% { opacity: 0.5; }';
    case 'float': return '  0%, 100% { transform: translateY(0); }\n  50% { transform: translateY(-10px); }';
    case 'spin': return '  from { transform: rotate(0deg); }\n  to { transform: rotate(360deg); }';
    case 'glow': return '  0%, 100% { box-shadow: 0 0 5px rgba(0,115,230,0.2); }\n  50% { box-shadow: 0 0 20px rgba(0,115,230,0.6); }';
    case 'shake': return '  0%, 100% { transform: translateX(0); }\n  25% { transform: translateX(-5px); }\n  75% { transform: translateX(5px); }';
    default: return null;
  }
}
