import { EditorElement } from '../types';
import { generateClassName } from './cssCompiler';

/**
 * Generates production-ready vanilla JavaScript for exported sites.
 * Handles: mobile nav toggle, smooth scroll, scroll animations,
 * accordion, tabs, modal, dropdown, countdown, form validation,
 * back-to-top, sticky navbar, and active link highlighting.
 */

// ─── Detect which interactive types exist in the element tree ────
interface FeatureFlags {
  hasNavbar: boolean;
  hasAccordion: boolean;
  hasTabs: boolean;
  hasModal: boolean;
  hasDropdown: boolean;
  hasCountdown: boolean;
  hasForm: boolean;
  hasScrollAnims: boolean;
  hasLinks: boolean;
  hasMarquee: boolean;
  hasTooltip: boolean;
  hasProgress: boolean;
}

function detectFeatures(elements: EditorElement[]): FeatureFlags {
  const flags: FeatureFlags = {
    hasNavbar: false, hasAccordion: false, hasTabs: false,
    hasModal: false, hasDropdown: false, hasCountdown: false,
    hasForm: false, hasScrollAnims: false, hasLinks: false,
    hasMarquee: false, hasTooltip: false, hasProgress: false,
  };

  function walk(el: EditorElement) {
    switch (el.type) {
      case 'navbar': flags.hasNavbar = true; break;
      case 'accordion': flags.hasAccordion = true; break;
      case 'tabs': flags.hasTabs = true; break;
      case 'modal': flags.hasModal = true; break;
      case 'dropdown': flags.hasDropdown = true; break;
      case 'countdown': flags.hasCountdown = true; break;
      case 'form': flags.hasForm = true; break;
      case 'marquee': flags.hasMarquee = true; break;
      case 'tooltip': flags.hasTooltip = true; break;
      case 'progress': flags.hasProgress = true; break;
      case 'link': case 'button': flags.hasLinks = true; break;
    }
    if (el.animations && el.animations.type !== 'none' &&
        (el.animations.trigger === 'onScroll' || el.animations.trigger === 'onView')) {
      flags.hasScrollAnims = true;
    }
    el.children.forEach(walk);
  }
  elements.forEach(walk);
  return flags;
}

// ─── Collect data attributes needed for JS targeting ─────────────
interface ElementJSData {
  className: string;
  type: string;
  props: Record<string, unknown>;
  animTrigger?: string;
  animType?: string;
}

function collectJSData(elements: EditorElement[]): ElementJSData[] {
  const items: ElementJSData[] = [];
  function walk(el: EditorElement) {
    const needsJS = ['navbar', 'accordion', 'tabs', 'modal', 'dropdown', 'countdown', 'form', 'marquee', 'tooltip'].includes(el.type)
      || (el.animations && el.animations.type !== 'none');
    if (needsJS) {
      items.push({
        className: generateClassName(el),
        type: el.type,
        props: el.props,
        animTrigger: el.animations?.trigger,
        animType: el.animations?.type,
      });
    }
    el.children.forEach(walk);
  }
  elements.forEach(walk);
  return items;
}

// ─── Generate the JavaScript string ──────────────────────────────
export function generateJS(elements: EditorElement[]): string {
  const flags = detectFeatures(elements);
  const jsData = collectJSData(elements);
  const sections: string[] = [];

  // Header
  sections.push(`/* ═══════════════════════════════════════════════
   Script.js — Auto-generated by Workshop
   Production-ready vanilla JavaScript
   ═══════════════════════════════════════════════ */

'use strict';

document.addEventListener('DOMContentLoaded', function() {
`);

  // ── Mobile Nav Toggle ──
  if (flags.hasNavbar) {
    sections.push(`
  // ── Mobile Navigation Toggle ──────────────────
  (function() {
    var navbars = document.querySelectorAll('nav');
    navbars.forEach(function(nav) {
      var links = nav.querySelectorAll('div');
      var menuBtn = null;

      // Create hamburger button for mobile
      var hamburger = document.createElement('button');
      hamburger.className = 'mobile-menu-toggle';
      hamburger.setAttribute('aria-label', 'Toggle menu');
      hamburger.innerHTML = '<span></span><span></span><span></span>';
      hamburger.style.cssText = 'display:none;flex-direction:column;gap:4px;background:none;border:none;cursor:pointer;padding:8px;z-index:100;';
      
      var spans = hamburger.querySelectorAll('span');
      spans.forEach(function(s) {
        s.style.cssText = 'display:block;width:20px;height:2px;background:#fff;transition:all 0.3s ease;';
      });

      nav.appendChild(hamburger);

      // Find the main links container (usually hidden on mobile)
      var linksContainer = null;
      links.forEach(function(div) {
        var style = window.getComputedStyle(div);
        if (div.children.length > 1 && div.querySelector('a')) {
          linksContainer = div;
        }
      });

      function updateMobile() {
        if (window.innerWidth <= 768) {
          hamburger.style.display = 'flex';
          if (linksContainer) {
            linksContainer.style.display = linksContainer.classList.contains('menu-open') ? 'flex' : 'none';
            linksContainer.style.flexDirection = 'column';
            linksContainer.style.position = 'absolute';
            linksContainer.style.top = '100%';
            linksContainer.style.left = '0';
            linksContainer.style.right = '0';
            linksContainer.style.backgroundColor = 'inherit';
            linksContainer.style.padding = '16px 24px';
            linksContainer.style.gap = '16px';
            linksContainer.style.zIndex = '99';
          }
        } else {
          hamburger.style.display = 'none';
          if (linksContainer) {
            linksContainer.style.display = '';
            linksContainer.style.flexDirection = '';
            linksContainer.style.position = '';
            linksContainer.style.top = '';
            linksContainer.style.left = '';
            linksContainer.style.right = '';
            linksContainer.style.padding = '';
            linksContainer.classList.remove('menu-open');
          }
        }
      }

      hamburger.addEventListener('click', function() {
        if (linksContainer) {
          linksContainer.classList.toggle('menu-open');
          var isOpen = linksContainer.classList.contains('menu-open');
          linksContainer.style.display = isOpen ? 'flex' : 'none';
          // Animate hamburger
          spans[0].style.transform = isOpen ? 'rotate(45deg) translate(4px, 4px)' : '';
          spans[1].style.opacity = isOpen ? '0' : '1';
          spans[2].style.transform = isOpen ? 'rotate(-45deg) translate(4px, -4px)' : '';
        }
      });

      window.addEventListener('resize', updateMobile);
      updateMobile();
    });
  })();
`);
  }

  // ── Smooth Scroll for Anchor Links (skip page links) ──
  if (flags.hasLinks) {
    sections.push(`
  // ── Smooth Scroll for Anchor Links ────────────
  document.querySelectorAll('a[href^="#"]').forEach(function(anchor) {
    anchor.addEventListener('click', function(e) {
      var targetId = this.getAttribute('href');
      if (targetId && targetId !== '#' && targetId.length > 1) {
        // Check if this is a same-page anchor (element exists on page)
        var target = document.querySelector(targetId);
        if (target) {
          e.preventDefault();
          target.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
        // If no matching element, let the browser handle it as a page link
        // (the HTML exporter converts #slug → slug.html)
      }
    });
  });
`);
  }

  // ── Scroll Animations (Intersection Observer) ──
  sections.push(`
  // ── Scroll Reveal Animations ──────────────────
  (function() {
    var animElements = document.querySelectorAll('[data-animate]');
    if (!animElements.length) return;

    var observer = new IntersectionObserver(function(entries) {
      entries.forEach(function(entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add('is-visible');
          observer.unobserve(entry.target);
        }
      });
    }, { threshold: 0.1, rootMargin: '0px 0px -50px 0px' });

    animElements.forEach(function(el) { observer.observe(el); });
  })();
`);

  // ── Accordion ──
  if (flags.hasAccordion) {
    sections.push(`
  // ── Accordion ─────────────────────────────────
  (function() {
    document.querySelectorAll('[data-accordion]').forEach(function(acc) {
      var trigger = acc.querySelector('[data-accordion-trigger]') || acc.firstElementChild;
      var content = acc.querySelector('[data-accordion-content]') || acc.lastElementChild;
      if (!trigger || !content || trigger === content) return;

      content.style.overflow = 'hidden';
      content.style.maxHeight = '0';
      content.style.transition = 'max-height 0.35s ease, opacity 0.35s ease';
      content.style.opacity = '0';

      trigger.style.cursor = 'pointer';
      trigger.addEventListener('click', function() {
        var isOpen = acc.classList.toggle('is-open');
        if (isOpen) {
          content.style.maxHeight = content.scrollHeight + 'px';
          content.style.opacity = '1';
        } else {
          content.style.maxHeight = '0';
          content.style.opacity = '0';
        }
      });
    });
  })();
`);
  }

  // ── Tabs ──
  if (flags.hasTabs) {
    sections.push(`
  // ── Tabs ──────────────────────────────────────
  (function() {
    document.querySelectorAll('[data-tabs]').forEach(function(tabGroup) {
      var triggers = tabGroup.querySelectorAll('[data-tab-trigger]');
      var panels = tabGroup.querySelectorAll('[data-tab-panel]');

      triggers.forEach(function(trigger, i) {
        trigger.style.cursor = 'pointer';
        trigger.addEventListener('click', function() {
          triggers.forEach(function(t) { t.classList.remove('is-active'); });
          panels.forEach(function(p) { p.style.display = 'none'; });
          trigger.classList.add('is-active');
          if (panels[i]) panels[i].style.display = '';
        });
      });

      // Default: show first tab
      if (panels.length) {
        panels.forEach(function(p, i) { p.style.display = i === 0 ? '' : 'none'; });
        if (triggers[0]) triggers[0].classList.add('is-active');
      }
    });
  })();
`);
  }

  // ── Modal ──
  if (flags.hasModal) {
    sections.push(`
  // ── Modal ─────────────────────────────────────
  (function() {
    document.querySelectorAll('[data-modal-trigger]').forEach(function(trigger) {
      var targetId = trigger.getAttribute('data-modal-trigger');
      var modal = document.querySelector('[data-modal="' + targetId + '"]');
      if (!modal) return;

      modal.style.cssText = 'display:none;position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,0.6);backdrop-filter:blur(4px);align-items:center;justify-content:center;';

      trigger.addEventListener('click', function() {
        modal.style.display = 'flex';
        document.body.style.overflow = 'hidden';
      });

      modal.addEventListener('click', function(e) {
        if (e.target === modal) {
          modal.style.display = 'none';
          document.body.style.overflow = '';
        }
      });

      var closeBtn = modal.querySelector('[data-modal-close]');
      if (closeBtn) {
        closeBtn.addEventListener('click', function() {
          modal.style.display = 'none';
          document.body.style.overflow = '';
        });
      }
    });

    // ESC key to close
    document.addEventListener('keydown', function(e) {
      if (e.key === 'Escape') {
        document.querySelectorAll('[data-modal]').forEach(function(m) {
          m.style.display = 'none';
        });
        document.body.style.overflow = '';
      }
    });
  })();
`);
  }

  // ── Dropdown ──
  if (flags.hasDropdown) {
    sections.push(`
  // ── Dropdown ──────────────────────────────────
  (function() {
    document.querySelectorAll('[data-dropdown]').forEach(function(dd) {
      var trigger = dd.querySelector('[data-dropdown-trigger]') || dd.firstElementChild;
      var menu = dd.querySelector('[data-dropdown-menu]') || dd.lastElementChild;
      if (!trigger || !menu || trigger === menu) return;

      menu.style.cssText = 'display:none;position:absolute;top:100%;left:0;min-width:180px;z-index:50;opacity:0;transform:translateY(-8px);transition:opacity 0.2s ease,transform 0.2s ease;';

      trigger.style.cursor = 'pointer';
      trigger.addEventListener('click', function(e) {
        e.stopPropagation();
        var isOpen = dd.classList.toggle('is-open');
        menu.style.display = isOpen ? 'block' : 'none';
        requestAnimationFrame(function() {
          menu.style.opacity = isOpen ? '1' : '0';
          menu.style.transform = isOpen ? 'translateY(0)' : 'translateY(-8px)';
        });
      });

      document.addEventListener('click', function() {
        dd.classList.remove('is-open');
        menu.style.display = 'none';
        menu.style.opacity = '0';
      });
    });
  })();
`);
  }

  // ── Countdown Timer ──
  if (flags.hasCountdown) {
    // Collect countdown data
    const countdowns = jsData.filter(d => d.type === 'countdown');
    sections.push(`
  // ── Countdown Timer ───────────────────────────
  (function() {
    var countdowns = document.querySelectorAll('[data-countdown]');
    countdowns.forEach(function(el) {
      var target = el.getAttribute('data-countdown');
      if (!target) {
        // Default: 24 hours from now
        var d = new Date();
        d.setHours(d.getHours() + 24);
        target = d.toISOString();
      }
      var endDate = new Date(target).getTime();
      var units = el.querySelectorAll('[data-unit]');

      function update() {
        var now = Date.now();
        var diff = Math.max(0, endDate - now);
        var days = Math.floor(diff / 86400000);
        var hours = Math.floor((diff % 86400000) / 3600000);
        var mins = Math.floor((diff % 3600000) / 60000);
        var secs = Math.floor((diff % 60000) / 1000);
        var vals = [days, hours, mins, secs];

        units.forEach(function(u, i) {
          var numEl = u.querySelector('[data-value]') || u.firstElementChild;
          if (numEl && vals[i] !== undefined) {
            numEl.textContent = String(vals[i]).padStart(2, '0');
          }
        });

        if (diff > 0) requestAnimationFrame(update);
      }
      update();
    });
  })();
`);
  }

  // ── Form Validation ──
  if (flags.hasForm) {
    sections.push(`
  // ── Form Validation ───────────────────────────
  (function() {
    document.querySelectorAll('form').forEach(function(form) {
      form.addEventListener('submit', function(e) {
        e.preventDefault();
        var valid = true;
        var inputs = form.querySelectorAll('input[required], textarea[required], select[required]');

        inputs.forEach(function(input) {
          input.style.borderColor = '';
          if (!input.value.trim()) {
            valid = false;
            input.style.borderColor = '#ef4444';
            input.style.transition = 'border-color 0.2s ease';
          }
          // Email validation
          if (input.type === 'email' && input.value) {
            var emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;
            if (!emailRegex.test(input.value)) {
              valid = false;
              input.style.borderColor = '#ef4444';
            }
          }
        });

        if (valid) {
          // Collect form data
          var formData = new FormData(form);
          var data = {};
          formData.forEach(function(value, key) { data[key] = value; });
          console.log('Form submitted:', data);
          
          // Show success state
          var btn = form.querySelector('button[type="submit"], a');
          if (btn) {
            var originalText = btn.textContent;
            btn.textContent = 'Sent ✓';
            btn.style.backgroundColor = '#22c55e';
            setTimeout(function() {
              btn.textContent = originalText;
              btn.style.backgroundColor = '';
              form.reset();
            }, 2000);
          }
        }
      });

      // Real-time validation feedback
      form.querySelectorAll('input, textarea').forEach(function(input) {
        input.addEventListener('blur', function() {
          if (input.hasAttribute('required') && !input.value.trim()) {
            input.style.borderColor = '#ef4444';
          } else {
            input.style.borderColor = '';
          }
        });
        input.addEventListener('input', function() {
          if (input.style.borderColor === 'rgb(239, 68, 68)') {
            input.style.borderColor = '';
          }
        });
      });
    });
  })();
`);
  }

  // ── Sticky Navbar ──
  if (flags.hasNavbar) {
    sections.push(`
  // ── Sticky Navbar ─────────────────────────────
  (function() {
    var nav = document.querySelector('nav');
    if (!nav) return;
    var navHeight = nav.offsetHeight;
    var lastScroll = 0;

    nav.style.position = 'sticky';
    nav.style.top = '0';
    nav.style.zIndex = '1000';
    nav.style.transition = 'transform 0.3s ease, box-shadow 0.3s ease';

    window.addEventListener('scroll', function() {
      var currentScroll = window.pageYOffset;
      if (currentScroll > navHeight) {
        nav.style.boxShadow = '0 4px 20px rgba(0,0,0,0.3)';
      } else {
        nav.style.boxShadow = '';
      }
      lastScroll = currentScroll;
    }, { passive: true });
  })();
`);
  }

  // ── Back to Top Button ──
  sections.push(`
  // ── Back to Top ───────────────────────────────
  (function() {
    var btn = document.createElement('button');
    btn.innerHTML = '↑';
    btn.setAttribute('aria-label', 'Back to top');
    btn.style.cssText = 'position:fixed;bottom:24px;right:24px;width:44px;height:44px;border-radius:50%;background:#000;color:#fff;border:1px solid rgba(255,255,255,0.1);font-size:18px;cursor:pointer;opacity:0;transform:translateY(10px);transition:all 0.3s ease;z-index:9998;display:flex;align-items:center;justify-content:center;';
    document.body.appendChild(btn);

    btn.addEventListener('click', function() {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    });

    window.addEventListener('scroll', function() {
      if (window.pageYOffset > 300) {
        btn.style.opacity = '1';
        btn.style.transform = 'translateY(0)';
      } else {
        btn.style.opacity = '0';
        btn.style.transform = 'translateY(10px)';
      }
    }, { passive: true });
  })();
`);

  // ── Active Link Highlighting ──
  if (flags.hasLinks) {
    sections.push(`
  // ── Active Link Highlighting ──────────────────
  (function() {
    var sections = document.querySelectorAll('section[id]');
    if (!sections.length) return;

    var observer = new IntersectionObserver(function(entries) {
      entries.forEach(function(entry) {
        if (entry.isIntersecting) {
          var id = entry.target.getAttribute('id');
          document.querySelectorAll('a[href="#' + id + '"]').forEach(function(a) {
            document.querySelectorAll('nav a').forEach(function(l) { l.style.opacity = '0.6'; });
            a.style.opacity = '1';
          });
        }
      });
    }, { threshold: 0.3 });

    sections.forEach(function(s) { observer.observe(s); });
  })();
`);
  }

  // ── Marquee ──
  if (flags.hasMarquee) {
    sections.push(`
  // ── Marquee Animation ─────────────────────────
  (function() {
    document.querySelectorAll('[data-marquee]').forEach(function(el) {
      var content = el.innerHTML;
      el.innerHTML = content + content;
      var speed = parseInt(el.getAttribute('data-marquee-speed')) || 30;
      el.style.cssText += 'display:flex;overflow:hidden;white-space:nowrap;';
      var inner = el.firstElementChild;
      if (inner) {
        inner.style.animation = 'marquee ' + speed + 's linear infinite';
      }
    });
  })();
`);
  }

  // ── Lazy Loading Images ──
  sections.push(`
  // ── Lazy Load Images ──────────────────────────
  (function() {
    var images = document.querySelectorAll('img[data-src]');
    if (!images.length) return;
    var imgObserver = new IntersectionObserver(function(entries) {
      entries.forEach(function(entry) {
        if (entry.isIntersecting) {
          var img = entry.target;
          img.src = img.getAttribute('data-src');
          img.removeAttribute('data-src');
          imgObserver.unobserve(img);
        }
      });
    });
    images.forEach(function(img) { imgObserver.observe(img); });
  })();
`);

  // ── Current Year in Footer ──
  sections.push(`
  // ── Auto-update Copyright Year ────────────────
  document.querySelectorAll('[data-year]').forEach(function(el) {
    el.textContent = new Date().getFullYear();
  });
`);

  // Close DOMContentLoaded
  sections.push(`
});
`);

  return sections.join('\n');
}
