import { ComponentDefinition } from '../types';

export const COMPONENT_REGISTRY: ComponentDefinition[] = [
  // ─── Layout ────────────────────────────────────────────
  {
    type: 'section',
    label: 'Section',
    icon: 'LayoutTemplate',
    category: 'Layout',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      desktop: { padding: '60px 40px', width: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center' },
    },
  },
  {
    type: 'container',
    label: 'Container',
    icon: 'Square',
    category: 'Layout',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      desktop: { maxWidth: '1200px', width: '100%', margin: '0 auto', padding: '20px' },
    },
  },
  {
    type: 'columns',
    label: 'Columns',
    icon: 'Columns3',
    category: 'Layout',
    canHaveChildren: true,
    defaultProps: { columnCount: 2 },
    defaultStyles: {
      desktop: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px', width: '100%' },
      tablet: { gridTemplateColumns: '1fr 1fr' },
      mobile: { gridTemplateColumns: '1fr' },
    },
  },
  {
    type: 'grid',
    label: 'Grid',
    icon: 'Grid3x3',
    category: 'Layout',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      desktop: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px', width: '100%' },
      mobile: { gridTemplateColumns: '1fr' },
    },
  },
  {
    type: 'spacer',
    label: 'Spacer',
    icon: 'MoveVertical',
    category: 'Layout',
    canHaveChildren: false,
    defaultProps: {},
    defaultStyles: { desktop: { height: '40px', width: '100%' } },
  },
  {
    type: 'divider',
    label: 'Divider',
    icon: 'Minus',
    category: 'Layout',
    canHaveChildren: false,
    defaultProps: {},
    defaultStyles: { desktop: { height: '1px', width: '100%', backgroundColor: '#e2e8f0' } },
  },
  {
    type: 'separator',
    label: 'Separator',
    icon: 'Minus',
    category: 'Layout',
    canHaveChildren: false,
    defaultProps: { style: 'gradient' },
    defaultStyles: { desktop: { height: '2px', width: '100%', background: 'linear-gradient(90deg, transparent, #3b82f6, transparent)' } },
  },

  // ─── Content ───────────────────────────────────────────
  {
    type: 'heading',
    label: 'Heading',
    icon: 'Type',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { text: 'Heading Text', level: 'h2' },
    defaultStyles: {
      desktop: { fontSize: '36px', fontWeight: '700', color: '#0f172a', lineHeight: '1.2' },
      mobile: { fontSize: '28px' },
    },
  },
  {
    type: 'text',
    label: 'Paragraph',
    icon: 'AlignLeft',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.' },
    defaultStyles: {
      desktop: { fontSize: '16px', color: '#475569', lineHeight: '1.7' },
    },
  },
  {
    type: 'button',
    label: 'Button',
    icon: 'MousePointerClick',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { text: 'Click Me', href: '#' },
    defaultStyles: {
      desktop: {
        padding: '12px 28px', backgroundColor: '#3b82f6', color: '#ffffff',
        borderRadius: '8px', fontSize: '16px', fontWeight: '600',
        cursor: 'pointer', border: 'none', display: 'inline-block',
      },
    },
  },
  {
    type: 'badge',
    label: 'Badge',
    icon: 'Tag',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { text: 'New' },
    defaultStyles: {
      desktop: {
        padding: '4px 12px', backgroundColor: '#eff6ff', color: '#3b82f6',
        borderRadius: '9999px', fontSize: '12px', fontWeight: '600', display: 'inline-block',
      },
    },
  },
  {
    type: 'card',
    label: 'Card',
    icon: 'CreditCard',
    category: 'Content',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      desktop: {
        padding: '24px', backgroundColor: '#ffffff', borderRadius: '12px',
        boxShadow: '0 1px 3px rgba(0,0,0,0.1)', border: '1px solid #e2e8f0',
      },
    },
  },
  {
    type: 'quote',
    label: 'Blockquote',
    icon: 'Quote',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
    defaultStyles: {
      desktop: {
        padding: '24px 32px', borderLeft: '4px solid #3b82f6',
        backgroundColor: '#f8fafc', fontSize: '18px', fontStyle: 'italic',
        color: '#334155', lineHeight: '1.6',
      },
    },
  },
  {
    type: 'list',
    label: 'List',
    icon: 'List',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { items: ['Item 1', 'Item 2', 'Item 3'], ordered: false },
    defaultStyles: {
      desktop: { fontSize: '16px', color: '#475569', lineHeight: '2', paddingLeft: '20px' },
    },
  },
  {
    type: 'code',
    label: 'Code Block',
    icon: 'Code',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { code: 'const hello = "world";', language: 'javascript' },
    defaultStyles: {
      desktop: {
        padding: '20px', backgroundColor: '#1e293b', color: '#e2e8f0',
        borderRadius: '8px', fontFamily: 'monospace', fontSize: '14px',
        lineHeight: '1.6', overflow: 'auto',
      },
    },
  },

  // ─── Media ─────────────────────────────────────────────
  {
    type: 'image',
    label: 'Image',
    icon: 'ImageIcon',
    category: 'Media',
    canHaveChildren: false,
    defaultProps: { src: 'https://placehold.co/600x400/e2e8f0/94a3b8?text=Image', alt: 'Image' },
    defaultStyles: {
      desktop: { width: '100%', maxWidth: '600px', height: 'auto', borderRadius: '8px', objectFit: 'cover' },
    },
  },
  {
    type: 'video',
    label: 'Video',
    icon: 'Video',
    category: 'Media',
    canHaveChildren: false,
    defaultProps: { src: '', poster: '' },
    defaultStyles: {
      desktop: { width: '100%', maxWidth: '800px', height: 'auto', borderRadius: '8px' },
    },
  },
  {
    type: 'icon',
    label: 'Icon',
    icon: 'Smile',
    category: 'Media',
    canHaveChildren: false,
    defaultProps: { iconName: 'Star', size: 24 },
    defaultStyles: { desktop: { color: '#3b82f6' } },
  },
  {
    type: 'audio',
    label: 'Audio',
    icon: 'Music',
    category: 'Media',
    canHaveChildren: false,
    defaultProps: { src: '' },
    defaultStyles: { desktop: { width: '100%' } },
  },
  {
    type: 'map',
    label: 'Map Embed',
    icon: 'MapPin',
    category: 'Media',
    canHaveChildren: false,
    defaultProps: { embedUrl: 'https://maps.google.com/maps?q=London&output=embed' },
    defaultStyles: { desktop: { width: '100%', height: '400px', borderRadius: '8px', border: 'none' } },
  },
  {
    type: 'lottie',
    label: 'Animation',
    icon: 'Sparkles',
    category: 'Media',
    canHaveChildren: false,
    defaultProps: { src: '', autoplay: true, loop: true },
    defaultStyles: { desktop: { width: '200px', height: '200px' } },
  },

  // ─── Interactive ───────────────────────────────────────
  {
    type: 'accordion',
    label: 'Accordion',
    icon: 'ChevronDown',
    category: 'Interactive',
    canHaveChildren: true,
    defaultProps: { title: 'Accordion Item', defaultOpen: false },
    defaultStyles: {
      desktop: { width: '100%', border: '1px solid #e2e8f0', borderRadius: '8px', overflow: 'hidden' },
    },
  },
  {
    type: 'tabs',
    label: 'Tabs',
    icon: 'LayoutList',
    category: 'Interactive',
    canHaveChildren: true,
    defaultProps: { tabs: ['Tab 1', 'Tab 2', 'Tab 3'], activeTab: 0 },
    defaultStyles: {
      desktop: { width: '100%' },
    },
  },
  {
    type: 'tooltip',
    label: 'Tooltip',
    icon: 'MessageCircle',
    category: 'Interactive',
    canHaveChildren: true,
    defaultProps: { tooltipText: 'Tooltip content here', position: 'top' },
    defaultStyles: {
      desktop: { display: 'inline-block' },
    },
  },
  {
    type: 'modal',
    label: 'Modal Trigger',
    icon: 'Maximize2',
    category: 'Interactive',
    canHaveChildren: true,
    defaultProps: { triggerText: 'Open Modal', modalTitle: 'Modal Title' },
    defaultStyles: {
      desktop: { display: 'inline-block' },
    },
  },
  {
    type: 'dropdown',
    label: 'Dropdown',
    icon: 'ChevronDown',
    category: 'Interactive',
    canHaveChildren: true,
    defaultProps: { label: 'Menu', items: ['Option 1', 'Option 2', 'Option 3'] },
    defaultStyles: {
      desktop: { display: 'inline-block', position: 'relative' },
    },
  },
  {
    type: 'slider',
    label: 'Slider',
    icon: 'SlidersHorizontal',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: { min: 0, max: 100, value: 50 },
    defaultStyles: {
      desktop: { width: '100%' },
    },
  },
  {
    type: 'marquee',
    label: 'Marquee',
    icon: 'MoveHorizontal',
    category: 'Interactive',
    canHaveChildren: true,
    defaultProps: { speed: 50, direction: 'left', pauseOnHover: true },
    defaultStyles: {
      desktop: { width: '100%', overflow: 'hidden' },
    },
  },

  // ─── Data ──────────────────────────────────────────────
  {
    type: 'countdown',
    label: 'Countdown',
    icon: 'Timer',
    category: 'Data',
    canHaveChildren: false,
    defaultProps: { targetDate: '2026-12-31T00:00:00', label: 'Coming Soon' },
    defaultStyles: {
      desktop: { display: 'flex', gap: '16px', justifyContent: 'center', fontSize: '36px', fontWeight: '700' },
    },
  },
  {
    type: 'progress',
    label: 'Progress Bar',
    icon: 'BarChart3',
    category: 'Data',
    canHaveChildren: false,
    defaultProps: { value: 65, max: 100, label: 'Progress', showValue: true },
    defaultStyles: {
      desktop: { width: '100%' },
    },
  },
  {
    type: 'table',
    label: 'Table',
    icon: 'Table',
    category: 'Data',
    canHaveChildren: false,
    defaultProps: {
      headers: ['Name', 'Role', 'Status'],
      rows: [['John', 'Developer', 'Active'], ['Jane', 'Designer', 'Active']],
    },
    defaultStyles: {
      desktop: { width: '100%', borderCollapse: 'collapse' },
    },
  },

  // ─── Forms ─────────────────────────────────────────────
  {
    type: 'form',
    label: 'Form',
    icon: 'FormInput',
    category: 'Forms',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      desktop: { display: 'flex', flexDirection: 'column', gap: '16px', width: '100%', maxWidth: '500px' },
    },
  },
  {
    type: 'input',
    label: 'Input',
    icon: 'TextCursorInput',
    category: 'Forms',
    canHaveChildren: false,
    defaultProps: { placeholder: 'Enter text...', inputType: 'text', label: 'Label' },
    defaultStyles: {
      desktop: {
        padding: '10px 14px', border: '1px solid #cbd5e1',
        borderRadius: '8px', fontSize: '14px', width: '100%',
      },
    },
  },
  {
    type: 'textarea',
    label: 'Textarea',
    icon: 'Text',
    category: 'Forms',
    canHaveChildren: false,
    defaultProps: { placeholder: 'Enter message...', label: 'Message' },
    defaultStyles: {
      desktop: {
        padding: '10px 14px', border: '1px solid #cbd5e1',
        borderRadius: '8px', fontSize: '14px', width: '100%',
        minHeight: '120px', resize: 'vertical',
      },
    },
  },
  {
    type: 'select',
    label: 'Select',
    icon: 'ChevronDown',
    category: 'Forms',
    canHaveChildren: false,
    defaultProps: { placeholder: 'Choose…', options: ['Option 1', 'Option 2', 'Option 3'], label: 'Select' },
    defaultStyles: {
      desktop: {
        padding: '10px 14px', border: '1px solid #cbd5e1',
        borderRadius: '8px', fontSize: '14px', width: '100%',
      },
    },
  },
  {
    type: 'checkbox',
    label: 'Checkbox',
    icon: 'CheckSquare',
    category: 'Forms',
    canHaveChildren: false,
    defaultProps: { label: 'I agree to the terms', checked: false },
    defaultStyles: {
      desktop: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '14px' },
    },
  },

  // ─── Navigation ────────────────────────────────────────
  {
    type: 'navbar',
    label: 'Navbar',
    icon: 'PanelTop',
    category: 'Navigation',
    canHaveChildren: true,
    defaultProps: { brand: 'Brand' },
    defaultStyles: {
      desktop: {
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        padding: '16px 40px', width: '100%', backgroundColor: '#ffffff',
        borderBottom: '1px solid #e2e8f0',
      },
    },
  },
  {
    type: 'footer',
    label: 'Footer',
    icon: 'PanelBottom',
    category: 'Navigation',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: {
      desktop: {
        padding: '40px', width: '100%', backgroundColor: '#0f172a',
        color: '#94a3b8', display: 'flex', justifyContent: 'center',
      },
    },
  },
  {
    type: 'link',
    label: 'Link',
    icon: 'Link',
    category: 'Navigation',
    canHaveChildren: false,
    defaultProps: { text: 'Link Text', href: '#' },
    defaultStyles: {
      desktop: { color: '#3b82f6', textDecoration: 'none', cursor: 'pointer', fontSize: '16px' },
    },
  },

  // ─── Advanced ──────────────────────────────────────────
  {
    type: 'html',
    label: 'Custom HTML',
    icon: 'Code',
    category: 'Advanced',
    canHaveChildren: false,
    defaultProps: { htmlContent: '<div>Custom HTML</div>' },
    defaultStyles: { desktop: { width: '100%' } },
  },
  {
    type: 'embed',
    label: 'Embed',
    icon: 'Globe',
    category: 'Advanced',
    canHaveChildren: false,
    defaultProps: { embedUrl: '' },
    defaultStyles: { desktop: { width: '100%', height: '400px' } },
  },

  // ─── Storefront / E-commerce (Interactive) ─────────────
  {
    type: 'product-grid',
    label: 'Product Grid',
    icon: 'Grid3x3',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: { columns: 4, showSearch: true, showCategories: true },
    defaultStyles: { desktop: { width: '100%', minHeight: '400px' } },
  },
  {
    type: 'booking-widget',
    label: 'Booking Widget',
    icon: 'Timer',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: {},
    defaultStyles: { desktop: { width: '100%', minHeight: '300px' } },
  },
  {
    type: 'booking-calendar',
    label: 'Appointment Calendar',
    icon: 'CalendarDays',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: {},
    defaultStyles: { desktop: { width: '100%', minHeight: '400px' } },
  },
  {
    type: 'service-list',
    label: 'Service List',
    icon: 'List',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: {},
    defaultStyles: { desktop: { width: '100%', minHeight: '200px' } },
  },
  {
    type: 'booking-button',
    label: 'Booking Button',
    icon: 'MousePointerClick',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: { text: 'Book Now' },
    defaultStyles: {
      desktop: {
        padding: '14px 32px', backgroundColor: '#22c55e', color: '#ffffff',
        borderRadius: '10px', fontSize: '16px', fontWeight: '600',
        cursor: 'pointer', border: 'none', display: 'inline-block',
      },
    },
  },
  {
    type: 'visitor-auth',
    label: 'Login / Signup',
    icon: 'FormInput',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: {},
    defaultStyles: { desktop: { width: '100%', minHeight: '200px' } },
  },
  {
    type: 'cart-button',
    label: 'Cart Button',
    icon: 'Tag',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: { text: 'Cart' },
    defaultStyles: { desktop: { display: 'inline-flex', padding: '10px 20px', backgroundColor: '#000', color: '#fff', borderRadius: '8px', fontSize: '14px', fontWeight: '600', cursor: 'pointer' } },
  },
  {
    type: 'visitor-dashboard',
    label: 'Customer Dashboard',
    icon: 'LayoutList',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: {},
    defaultStyles: { desktop: { width: '100%', minHeight: '400px' } },
  },

  // ─── Marketing ─────────────────────────────────────────
  {
    type: 'testimonial-card',
    label: 'Testimonial',
    icon: 'Quote',
    category: 'Marketing',
    canHaveChildren: false,
    defaultProps: { text: '"This product changed everything for our business."', author: 'Jane Smith', role: 'CEO, Acme Inc', rating: 5 },
    defaultStyles: {
      desktop: { padding: '32px', backgroundColor: '#ffffff', borderRadius: '12px', boxShadow: '0 2px 12px rgba(0,0,0,0.08)', border: '1px solid #f0f0f0', maxWidth: '480px' },
    },
  },
  {
    type: 'trust-badge',
    label: 'Trust Badge',
    icon: 'Tag',
    category: 'Marketing',
    canHaveChildren: false,
    defaultProps: { text: 'Trusted by 10,000+ Companies', icon: 'shield' },
    defaultStyles: {
      desktop: { display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '8px 16px', backgroundColor: '#f0fdf4', color: '#166534', borderRadius: '8px', fontSize: '13px', fontWeight: '600', border: '1px solid #bbf7d0' },
    },
  },
  {
    type: 'rating-stars',
    label: 'Star Rating',
    icon: 'Sparkles',
    category: 'Marketing',
    canHaveChildren: false,
    defaultProps: { rating: 4.8, count: 128 },
    defaultStyles: {
      desktop: { display: 'inline-flex', alignItems: 'center', gap: '6px', fontSize: '14px', color: '#f59e0b' },
    },
  },
  {
    type: 'pricing-card',
    label: 'Pricing Card',
    icon: 'CreditCard',
    category: 'Marketing',
    canHaveChildren: true,
    defaultProps: { plan: 'Pro', price: '£49', period: '/month', featured: true, features: ['Unlimited Projects', '24/7 Support', 'Custom Domain', 'Analytics'] },
    defaultStyles: {
      desktop: { padding: '40px 32px', backgroundColor: '#ffffff', borderRadius: '16px', boxShadow: '0 4px 24px rgba(0,0,0,0.1)', border: '2px solid #3b82f6', textAlign: 'center', maxWidth: '360px' },
    },
  },
  {
    type: 'cta-banner',
    label: 'CTA Banner',
    icon: 'LayoutTemplate',
    category: 'Marketing',
    canHaveChildren: true,
    defaultProps: { headline: 'Ready to Get Started?', subtext: 'Join thousands of happy customers today.', buttonText: 'Start Free Trial' },
    defaultStyles: {
      desktop: { padding: '60px 40px', backgroundColor: '#1e3a5f', color: '#ffffff', textAlign: 'center', borderRadius: '16px', width: '100%' },
    },
  },
  {
    type: 'newsletter-form',
    label: 'Newsletter Form',
    icon: 'FormInput',
    category: 'Marketing',
    canHaveChildren: false,
    defaultProps: { placeholder: 'Enter your email', buttonText: 'Subscribe', heading: 'Stay Updated' },
    defaultStyles: {
      desktop: { padding: '40px', backgroundColor: '#f8fafc', borderRadius: '12px', textAlign: 'center', width: '100%', maxWidth: '520px' },
    },
  },
  {
    type: 'feature-card',
    label: 'Feature Card',
    icon: 'Sparkles',
    category: 'Marketing',
    canHaveChildren: false,
    defaultProps: { icon: 'Zap', title: 'Lightning Fast', description: 'Built for speed with optimized performance at every level.' },
    defaultStyles: {
      desktop: { padding: '28px', backgroundColor: '#ffffff', borderRadius: '12px', border: '1px solid #e2e8f0' },
    },
  },
  {
    type: 'stat-card',
    label: 'Stat Counter',
    icon: 'BarChart3',
    category: 'Marketing',
    canHaveChildren: false,
    defaultProps: { value: '10K+', label: 'Active Users', prefix: '', suffix: '' },
    defaultStyles: {
      desktop: { textAlign: 'center', padding: '24px' },
    },
  },

  // ─── Social ────────────────────────────────────────────
  {
    type: 'social-icons',
    label: 'Social Icons',
    icon: 'Globe',
    category: 'Social',
    canHaveChildren: false,
    defaultProps: { platforms: ['twitter', 'instagram', 'linkedin', 'facebook'], size: 'md' },
    defaultStyles: {
      desktop: { display: 'flex', gap: '12px', alignItems: 'center' },
    },
  },
  {
    type: 'social-share',
    label: 'Share Buttons',
    icon: 'Globe',
    category: 'Social',
    canHaveChildren: false,
    defaultProps: { platforms: ['twitter', 'facebook', 'linkedin'], label: 'Share this page' },
    defaultStyles: {
      desktop: { display: 'flex', gap: '8px', alignItems: 'center' },
    },
  },
  {
    type: 'review-widget',
    label: 'Review Widget',
    icon: 'MessageCircle',
    category: 'Social',
    canHaveChildren: false,
    defaultProps: { source: 'google', rating: 4.9, reviewCount: 256 },
    defaultStyles: {
      desktop: { padding: '20px', backgroundColor: '#ffffff', borderRadius: '12px', border: '1px solid #e2e8f0', display: 'inline-flex', alignItems: 'center', gap: '12px' },
    },
  },
  {
    type: 'avatar-group',
    label: 'Avatar Group',
    icon: 'Smile',
    category: 'Social',
    canHaveChildren: false,
    defaultProps: { count: 5, size: 36, overlap: 8 },
    defaultStyles: {
      desktop: { display: 'flex', alignItems: 'center' },
    },
  },

  // ─── Charts ────────────────────────────────────────────
  {
    type: 'bar-chart',
    label: 'Bar Chart',
    icon: 'BarChart3',
    category: 'Charts',
    canHaveChildren: false,
    defaultProps: { data: [65, 80, 45, 90, 55], labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], color: '#3b82f6' },
    defaultStyles: {
      desktop: { width: '100%', height: '300px', padding: '20px', backgroundColor: '#ffffff', borderRadius: '12px', border: '1px solid #e2e8f0' },
    },
  },
  {
    type: 'line-chart',
    label: 'Line Chart',
    icon: 'BarChart3',
    category: 'Charts',
    canHaveChildren: false,
    defaultProps: { data: [30, 45, 60, 55, 80, 90], labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], color: '#10b981' },
    defaultStyles: {
      desktop: { width: '100%', height: '300px', padding: '20px', backgroundColor: '#ffffff', borderRadius: '12px', border: '1px solid #e2e8f0' },
    },
  },
  {
    type: 'pie-chart',
    label: 'Pie Chart',
    icon: 'BarChart3',
    category: 'Charts',
    canHaveChildren: false,
    defaultProps: { data: [35, 25, 20, 20], labels: ['Organic', 'Paid', 'Social', 'Direct'], colors: ['#3b82f6', '#10b981', '#f59e0b', '#ef4444'] },
    defaultStyles: {
      desktop: { width: '300px', height: '300px', padding: '20px', backgroundColor: '#ffffff', borderRadius: '12px', border: '1px solid #e2e8f0' },
    },
  },

  // ─── Advanced Interactive ──────────────────────────────
  {
    type: 'breadcrumb',
    label: 'Breadcrumb',
    icon: 'Link',
    category: 'Navigation',
    canHaveChildren: false,
    defaultProps: { items: ['Home', 'Products', 'Category', 'Current Page'], separator: '/' },
    defaultStyles: {
      desktop: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '14px', color: '#64748b' },
    },
  },
  {
    type: 'mega-menu',
    label: 'Mega Menu',
    icon: 'LayoutList',
    category: 'Navigation',
    canHaveChildren: true,
    defaultProps: { columns: 3, heading: 'Products' },
    defaultStyles: {
      desktop: { width: '100%', padding: '32px', backgroundColor: '#ffffff', borderRadius: '12px', boxShadow: '0 8px 32px rgba(0,0,0,0.12)', display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '24px' },
    },
  },
  {
    type: 'carousel',
    label: 'Carousel',
    icon: 'SlidersHorizontal',
    category: 'Interactive',
    canHaveChildren: true,
    defaultProps: { autoplay: true, interval: 5000, showDots: true, showArrows: true },
    defaultStyles: {
      desktop: { width: '100%', overflow: 'hidden', borderRadius: '12px', position: 'relative' },
    },
  },
  {
    type: 'lightbox',
    label: 'Lightbox',
    icon: 'Maximize2',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: { src: 'https://placehold.co/800x600/e2e8f0/94a3b8?text=Image', alt: 'Gallery image' },
    defaultStyles: {
      desktop: { cursor: 'pointer', borderRadius: '8px', overflow: 'hidden' },
    },
  },
  {
    type: 'stepper',
    label: 'Stepper',
    icon: 'LayoutList',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: { steps: ['Account', 'Details', 'Payment', 'Confirm'], currentStep: 1 },
    defaultStyles: {
      desktop: { width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '12px', padding: '20px' },
    },
  },

  // ─── Animated & Interactive (NEW) ──────────────────────
  {
    type: 'animated-counter',
    label: 'Animated Counter',
    icon: 'BarChart3',
    category: 'Data',
    canHaveChildren: false,
    defaultProps: { endValue: 2500, prefix: '', suffix: '+', label: 'Happy Clients', duration: 2 },
    defaultStyles: { desktop: { textAlign: 'center', padding: '24px' } },
  },
  {
    type: 'gradient-text',
    label: 'Gradient Text',
    icon: 'Type',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { text: 'Stunning Gradient', gradient: 'linear-gradient(135deg, #667eea, #764ba2)', level: 'h2' },
    defaultStyles: { desktop: { fontSize: '48px', fontWeight: '800', letterSpacing: '-0.03em', lineHeight: '1.1' } },
  },
  {
    type: 'typing-text',
    label: 'Typing Effect',
    icon: 'Type',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { texts: ['Build faster.', 'Ship smarter.', 'Scale effortlessly.'], speed: 80, loop: true },
    defaultStyles: { desktop: { fontSize: '36px', fontWeight: '700', color: '#fff', fontFamily: 'monospace' } },
  },
  {
    type: 'before-after',
    label: 'Before / After',
    icon: 'SlidersHorizontal',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: { beforeSrc: 'https://placehold.co/600x400/1e293b/94a3b8?text=Before', afterSrc: 'https://placehold.co/600x400/3b82f6/ffffff?text=After', position: 50 },
    defaultStyles: { desktop: { width: '100%', maxWidth: '700px', height: '400px', borderRadius: '12px', overflow: 'hidden', position: 'relative' } },
  },
  {
    type: 'scroll-progress',
    label: 'Scroll Progress',
    icon: 'BarChart3',
    category: 'Data',
    canHaveChildren: false,
    defaultProps: { color: '#3b82f6', height: 3, position: 'top' },
    defaultStyles: { desktop: { width: '100%' } },
  },
  {
    type: 'video-background',
    label: 'Video BG Section',
    icon: 'Video',
    category: 'Layout',
    canHaveChildren: true,
    defaultProps: { videoUrl: '', posterUrl: '', overlay: 'rgba(0,0,0,0.5)' },
    defaultStyles: { desktop: { position: 'relative', minHeight: '500px', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' } },
  },
  {
    type: 'parallax-section',
    label: 'Parallax Section',
    icon: 'LayoutTemplate',
    category: 'Layout',
    canHaveChildren: true,
    defaultProps: { bgImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=1080&fit=crop', speed: 0.5 },
    defaultStyles: { desktop: { position: 'relative', minHeight: '500px', backgroundAttachment: 'fixed', backgroundSize: 'cover', backgroundPosition: 'center', display: 'flex', alignItems: 'center', justifyContent: 'center' } },
  },
  {
    type: 'icon-box',
    label: 'Icon Box',
    icon: 'Square',
    category: 'Marketing',
    canHaveChildren: false,
    defaultProps: { icon: '🚀', title: 'Fast Delivery', description: 'Get your project done in record time.', style: 'bordered' },
    defaultStyles: { desktop: { padding: '32px', backgroundColor: '#ffffff', borderRadius: '16px', border: '1px solid #e2e8f0', textAlign: 'center' } },
  },
  {
    type: 'logo-cloud',
    label: 'Logo Cloud',
    icon: 'Grid3x3',
    category: 'Marketing',
    canHaveChildren: false,
    defaultProps: { logos: ['Google', 'Microsoft', 'Apple', 'Amazon', 'Meta', 'Netflix'], style: 'grid' },
    defaultStyles: { desktop: { display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: '32px', alignItems: 'center', padding: '40px', opacity: '0.5' } },
  },
  {
    type: 'comparison-table',
    label: 'Comparison Table',
    icon: 'Table',
    category: 'Data',
    canHaveChildren: false,
    defaultProps: { headers: ['Feature', 'Free', 'Pro', 'Enterprise'], rows: [['Users', '1', '10', 'Unlimited'], ['Storage', '1GB', '100GB', 'Unlimited'], ['Support', 'Email', 'Priority', '24/7 Dedicated']] },
    defaultStyles: { desktop: { width: '100%', borderCollapse: 'collapse', borderRadius: '12px', overflow: 'hidden' } },
  },
  {
    type: 'timeline',
    label: 'Timeline',
    icon: 'LayoutList',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { items: [{ year: '2020', title: 'Founded', desc: 'Started our journey' }, { year: '2022', title: 'Series A', desc: 'Raised $10M' }, { year: '2024', title: '10K Users', desc: 'Reached milestone' }] },
    defaultStyles: { desktop: { width: '100%', padding: '40px' } },
  },
  {
    type: 'masonry-gallery',
    label: 'Masonry Gallery',
    icon: 'Grid3x3',
    category: 'Media',
    canHaveChildren: false,
    defaultProps: { images: ['photo-1618005182384-a83a8bd57fbe', 'photo-1497366216548-37526070297c', 'photo-1558618666-fcd25c85f82e', 'photo-1460925895917-afdab827c52f', 'photo-1551288049-bebda4e38f71', 'photo-1552664730-d307ca884978'], columns: 3 },
    defaultStyles: { desktop: { width: '100%' } },
  },
  {
    type: 'floating-card',
    label: 'Floating Card',
    icon: 'CreditCard',
    category: 'Content',
    canHaveChildren: true,
    defaultProps: { elevation: 'high' },
    defaultStyles: { desktop: { padding: '32px', backgroundColor: '#ffffff', borderRadius: '20px', boxShadow: '0 20px 60px rgba(0,0,0,0.15), 0 0 0 1px rgba(0,0,0,0.05)', transform: 'translateY(0)', transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)' } },
  },
  {
    type: 'glassmorphism-card',
    label: 'Glass Card',
    icon: 'CreditCard',
    category: 'Content',
    canHaveChildren: true,
    defaultProps: {},
    defaultStyles: { desktop: { padding: '32px', backgroundColor: 'rgba(255,255,255,0.1)', backdropFilter: 'blur(20px)', borderRadius: '16px', border: '1px solid rgba(255,255,255,0.2)', boxShadow: '0 8px 32px rgba(0,0,0,0.1)' } },
  },
  {
    type: 'morphing-blob',
    label: 'Blob / Shape',
    icon: 'Sparkles',
    category: 'Media',
    canHaveChildren: false,
    defaultProps: { color1: '#667eea', color2: '#764ba2', size: 300 },
    defaultStyles: { desktop: { width: '300px', height: '300px' } },
  },
  {
    type: 'particle-field',
    label: 'Particle Field',
    icon: 'Sparkles',
    category: 'Media',
    canHaveChildren: false,
    defaultProps: { count: 50, color: '#3b82f6', speed: 1 },
    defaultStyles: { desktop: { width: '100%', height: '400px', position: 'relative' } },
  },
  {
    type: 'text-reveal',
    label: 'Text Reveal',
    icon: 'Type',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { text: 'Reveal On Scroll', style: 'wipe' },
    defaultStyles: { desktop: { fontSize: '64px', fontWeight: '800', color: '#fff', letterSpacing: '-0.04em' } },
  },

  // ─── New Webflow/WordPress Components ──────────────────
  {
    type: 'hamburger-menu',
    label: 'Hamburger Menu',
    icon: 'Menu',
    category: 'Navigation',
    canHaveChildren: true,
    defaultProps: { style: 'lines', animated: true },
    defaultStyles: { desktop: { width: '40px', height: '40px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', borderRadius: '8px' } },
  },
  {
    type: 'search-bar',
    label: 'Search Bar',
    icon: 'Search',
    category: 'Forms',
    canHaveChildren: false,
    defaultProps: { placeholder: 'Search…', icon: 'search', buttonText: 'Search' },
    defaultStyles: { desktop: { display: 'flex', width: '100%', maxWidth: '480px', height: '44px', borderRadius: '12px', border: '1px solid #e2e8f0', overflow: 'hidden' } },
  },
  {
    type: 'pagination',
    label: 'Pagination',
    icon: 'ChevronDown',
    category: 'Navigation',
    canHaveChildren: false,
    defaultProps: { totalPages: 10, currentPage: 1, showPrevNext: true, showFirstLast: false },
    defaultStyles: { desktop: { display: 'flex', alignItems: 'center', gap: '4px', justifyContent: 'center' } },
  },
  {
    type: 'tag-pill',
    label: 'Tag / Pill',
    icon: 'Tag',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { text: 'Tag', variant: 'filled', color: '#3b82f6', removable: false },
    defaultStyles: { desktop: { display: 'inline-flex', alignItems: 'center', gap: '6px', padding: '4px 12px', borderRadius: '9999px', fontSize: '12px', fontWeight: '500' } },
  },
  {
    type: 'alert-banner',
    label: 'Alert Banner',
    icon: 'AlertCircle',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { text: 'This is an important message.', variant: 'info', dismissible: true, icon: true },
    defaultStyles: { desktop: { padding: '14px 20px', borderRadius: '10px', width: '100%', display: 'flex', alignItems: 'center', gap: '12px', fontSize: '14px' } },
  },
  {
    type: 'avatar',
    label: 'Avatar',
    icon: 'User',
    category: 'Content',
    canHaveChildren: false,
    defaultProps: { src: '', initials: 'JD', size: 48, status: 'online' },
    defaultStyles: { desktop: { borderRadius: '50%', overflow: 'hidden', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', backgroundColor: '#3b82f6', color: '#ffffff', fontWeight: '600' } },
  },
  {
    type: 'switch-toggle',
    label: 'Toggle Switch',
    icon: 'ToggleLeft',
    category: 'Forms',
    canHaveChildren: false,
    defaultProps: { label: 'Enable feature', checked: false, size: 'md' },
    defaultStyles: { desktop: { display: 'flex', alignItems: 'center', gap: '12px', cursor: 'pointer' } },
  },
  {
    type: 'range-slider',
    label: 'Range Slider',
    icon: 'SlidersHorizontal',
    category: 'Forms',
    canHaveChildren: false,
    defaultProps: { min: 0, max: 100, value: 50, label: 'Volume', showValue: true, step: 1 },
    defaultStyles: { desktop: { width: '100%', padding: '8px 0' } },
  },
  {
    type: 'file-upload',
    label: 'File Upload',
    icon: 'Upload',
    category: 'Forms',
    canHaveChildren: false,
    defaultProps: { label: 'Drop files here or click to upload', accept: 'image/*', multiple: false, maxSize: 10 },
    defaultStyles: { desktop: { width: '100%', minHeight: '160px', border: '2px dashed #cbd5e1', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', flexDirection: 'column', gap: '8px', cursor: 'pointer', padding: '24px' } },
  },
  {
    type: 'date-picker',
    label: 'Date Picker',
    icon: 'CalendarDays',
    category: 'Forms',
    canHaveChildren: false,
    defaultProps: { label: 'Select date', placeholder: 'DD/MM/YYYY', format: 'dd/MM/yyyy' },
    defaultStyles: { desktop: { width: '100%', maxWidth: '280px' } },
  },
  {
    type: 'star-rating',
    label: 'Star Rating',
    icon: 'Star',
    category: 'Interactive',
    canHaveChildren: false,
    defaultProps: { value: 4, max: 5, size: 24, color: '#f59e0b', interactive: true },
    defaultStyles: { desktop: { display: 'inline-flex', gap: '4px', alignItems: 'center' } },
  },
  {
    type: 'back-to-top',
    label: 'Back to Top',
    icon: 'ArrowUp',
    category: 'Navigation',
    canHaveChildren: false,
    defaultProps: { icon: 'ArrowUp', showAfter: 300, smooth: true },
    defaultStyles: { desktop: { position: 'fixed', bottom: '24px', right: '24px', width: '48px', height: '48px', borderRadius: '50%', backgroundColor: '#3b82f6', color: '#ffffff', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', boxShadow: '0 4px 16px rgba(0,0,0,0.15)', zIndex: '50' } },
  },
  {
    type: 'popover',
    label: 'Popover',
    icon: 'MessageCircle',
    category: 'Interactive',
    canHaveChildren: true,
    defaultProps: { triggerText: 'Hover me', position: 'top' },
    defaultStyles: { desktop: { display: 'inline-block', position: 'relative' } },
  },
  {
    type: 'sidebar',
    label: 'Sidebar',
    icon: 'PanelLeft',
    category: 'Layout',
    canHaveChildren: true,
    defaultProps: { position: 'left', width: '280px' },
    defaultStyles: { desktop: { width: '280px', minHeight: '500px', backgroundColor: '#ffffff', borderRight: '1px solid #e2e8f0', padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px' } },
  },
  {
    type: 'sticky-bar',
    label: 'Sticky Bar',
    icon: 'PanelTop',
    category: 'Navigation',
    canHaveChildren: true,
    defaultProps: { position: 'top', dismissible: true },
    defaultStyles: { desktop: { width: '100%', padding: '12px 24px', backgroundColor: '#3b82f6', color: '#ffffff', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '16px', fontSize: '14px', fontWeight: '500' } },
  },
  {
    type: 'cookie-banner',
    label: 'Cookie Banner',
    icon: 'Shield',
    category: 'Navigation',
    canHaveChildren: false,
    defaultProps: { text: 'We use cookies to improve your experience.', acceptText: 'Accept', declineText: 'Decline', position: 'bottom' },
    defaultStyles: { desktop: { position: 'fixed', bottom: '0', left: '0', right: '0', padding: '20px 32px', backgroundColor: '#1e293b', color: '#e2e8f0', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '24px', fontSize: '14px', zIndex: '9999' } },
  },
];
