import { useState, useEffect, useCallback, useRef } from 'react';
import { Monitor, Tablet, Smartphone, Plus, Sparkles, ZoomIn, ZoomOut, Maximize } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { EditorElement } from '../types';
import { SectionBlock, ALL_SECTION_BLOCKS } from '../constants/sectionBlocks';
import { WireframeSectionEditor } from './WireframeSectionEditor';
import { WireframeAddSectionPanel } from './WireframeAddSectionPanel';
import { AIWireframeGenerator } from './AIWireframeGenerator';
import { WireframeBuildingAnimation } from './WireframeBuildingAnimation';
import { generateWireframes } from './wireframeGenerator';
import { useSitePagesSync, notifySitePagesUpdated } from './useSitePagesSync';
import { toast } from '@/hooks/use-toast';

/** Inject inter-page links into navbar link elements */
function injectNavLinks(elements: EditorElement[], allPages: { name: string; slug: string }[]) {
  function walk(el: EditorElement) {
    // If this is a link inside a navbar-like parent, try to match by text
    if (el.type === 'link' && el.props?.text) {
      const text = (el.props.text as string).toLowerCase();
      const match = allPages.find(p => p.name.toLowerCase() === text || p.slug.replace('/', '') === text);
      if (match) {
        el.props.href = `#${match.slug.replace(/^\//, '') || 'index'}`;
      }
    }
    el.children?.forEach(c => walk(c));
  }
  elements.forEach(el => walk(el));
}

function renderPageHTML(elements: EditorElement[]): string {
  return elements.map(el => renderEl(el)).join('');
}

function renderEl(el: EditorElement): string {
  const style = Object.entries((el.styles?.desktop || {}) as Record<string, unknown>)
    .filter(([, v]) => v != null && v !== '')
    .map(([k, v]) => `${k.replace(/[A-Z]/g, m => '-' + m.toLowerCase())}:${v}`)
    .join(';');

  const children = el.children?.length ? el.children.map(c => renderEl(c)).join('') : '';
  const text = el.props?.text ? String(el.props.text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\n/g, '<br/>') : '';

  if (el.type === 'image') {
    const src = (el.props?.src as string) || '';
    return `<img src="${src.replace(/"/g, '&quot;')}" alt="" style="${style}; display:block; max-width:100%;" loading="lazy" />`;
  }
  if (el.type === 'spacer') return `<div style="${style}"></div>`;
  if (el.type === 'divider') return `<hr style="${style}; border:none; height:1px; background:rgba(255,255,255,0.1);" />`;

  const tag = el.type === 'navbar' ? 'nav' : el.type === 'footer' ? 'footer' : el.type === 'section' ? 'section' : el.type === 'text' ? 'p' : 'div';
  return `<${tag} style="${style}">${text}${children}</${tag}>`;
}

interface WireframeViewerProps {
  siteId?: string;
  onNavigateToPage?: (pageId: string) => void;
}

export function WireframeViewer({ siteId, onNavigateToPage }: WireframeViewerProps) {
  const { pages, loading, reload: loadPages, setPages } = useSitePagesSync(siteId);
  const [device, setDevice] = useState<'desktop' | 'tablet' | 'mobile'>('desktop');
  const [selectedPageId, setSelectedPageId] = useState<string | null>(null);
  const [selectedSectionIdx, setSelectedSectionIdx] = useState<number | null>(null);
  const [showAddPanel, setShowAddPanel] = useState(false);
  const [showAIGenerator, setShowAIGenerator] = useState(false);

  // Auto-generation state
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  const [autoGenProgress, setAutoGenProgress] = useState('');
  const [showBuildAnimation, setShowBuildAnimation] = useState(false);
  const hasAutoGenerated = useRef(false);

  // Canvas state
  const [canvasZoom, setCanvasZoom] = useState(1);
  const [panOffset, setPanOffset] = useState({ x: 0, y: 0 });
  const [isPanning, setIsPanning] = useState(false);
  const panStart = useRef({ x: 0, y: 0 });
  const panOffsetStart = useRef({ x: 0, y: 0 });
  const canvasRef = useRef<HTMLDivElement>(null);
  const zoomRef = useRef(canvasZoom);
  const panRef = useRef(panOffset);
  zoomRef.current = canvasZoom;
  panRef.current = panOffset;

  const cardWidth = device === 'desktop' ? 340 : device === 'tablet' ? 240 : 160;
  const previewWidth = device === 'desktop' ? 1280 : device === 'tablet' ? 768 : 375;
  const scale = cardWidth / previewWidth;

  // loadPages and pages come from useSitePagesSync

  // Auto-generate wireframes when sitemap pages exist but have no elements
  useEffect(() => {
    if (loading || hasAutoGenerated.current || pages.length === 0) return;
    const allEmpty = pages.every(p => !p.elements || p.elements.length === 0);
    if (!allEmpty) return;

    hasAutoGenerated.current = true;
    setShowBuildAnimation(true);

    const autoGenerate = async () => {
      setIsAutoGenerating(true);
      setAutoGenProgress('Analyzing sitemap pages…');

      try {
        const sectionIds = ALL_SECTION_BLOCKS.map(b => b.id);
        const pageDescriptions = pages.map(p => `${p.page_name} (${p.slug})`).join(', ');

        setAutoGenProgress('Generating wireframe layouts…');

        const aiPages = generateWireframes(
          `Generate wireframe sections for these existing sitemap pages: ${pageDescriptions}. Match section types to each page's purpose.`,
          pages.length,
          sectionIds
        );

        // Build a list of all page names + slugs for nav linking
        const allPageLinks = pages.map(p => ({ name: p.page_name, slug: p.slug }));

        // Match AI pages to existing DB pages and update elements
        for (let i = 0; i < aiPages.length; i++) {
          const aiPage = aiPages[i];
          setAutoGenProgress(`Building page ${i + 1}/${aiPages.length}: ${aiPage.page_name}`);

          // Resolve section IDs to actual elements
          const elements: EditorElement[] = [];
          for (const sectionId of aiPage.sections) {
            const block = ALL_SECTION_BLOCKS.find(b => b.id === sectionId);
            if (block) {
              const fresh = JSON.parse(JSON.stringify(block.elements)) as EditorElement[];
              const assignIds = (el: EditorElement) => {
                el.id = crypto.randomUUID();
                el.children?.forEach(assignIds);
              };
              fresh.forEach(assignIds);
              elements.push(...fresh);
            }
          }

          // Inject inter-page links into navbar elements
          injectNavLinks(elements, allPageLinks);

          // Find matching existing page by slug or index
          const matchedPage = pages.find(p => p.slug === aiPage.slug) || pages[i];
          if (matchedPage) {
            await supabase.from('designer_pages').update({ elements: elements as any }).eq('id', matchedPage.id);
          }
        }

        setAutoGenProgress('Wireframes complete!');
        toast({ title: `Generated wireframes for ${aiPages.length} pages!` });
        notifySitePagesUpdated();

        // Reload pages with new elements
        await loadPages();
      } catch (err: any) {
        console.error('Auto-generation error:', err);
        toast({ title: 'Auto-generation failed', description: err.message, variant: 'destructive' });
      } finally {
        setIsAutoGenerating(false);
      }
    };

    autoGenerate();
  }, [loading, pages, loadPages]);

  // Wheel zoom
  useEffect(() => {
    const el = canvasRef.current;
    if (!el) return;
    const onWheel = (e: WheelEvent) => {
      e.preventDefault();
      e.stopPropagation();
      const factor = e.deltaY > 0 ? 0.85 : 1.15;
      const rect = el.getBoundingClientRect();
      const mouseX = e.clientX - rect.left;
      const mouseY = e.clientY - rect.top;

      const prevZoom = zoomRef.current;
      const newZoom = Math.min(3, Math.max(0.1, prevZoom * factor));
      const ratio = newZoom / prevZoom;
      const prev = panRef.current;

      setPanOffset({
        x: mouseX - ratio * (mouseX - prev.x),
        y: mouseY - ratio * (mouseY - prev.y),
      });
      setCanvasZoom(newZoom);
    };
    el.addEventListener('wheel', onWheel, { passive: false });
    return () => el.removeEventListener('wheel', onWheel);
  }, [loading]);

  // Middle-mouse pan
  useEffect(() => {
    const el = canvasRef.current;
    if (!el) return;

    const onDown = (e: PointerEvent) => {
      if (e.button !== 1) return; // middle click only
      e.preventDefault();
      setIsPanning(true);
      panStart.current = { x: e.clientX, y: e.clientY };
      panOffsetStart.current = { ...panOffset };
      el.setPointerCapture(e.pointerId);
    };
    const onMove = (e: PointerEvent) => {
      if (!isPanning) return;
      setPanOffset({
        x: panOffsetStart.current.x + (e.clientX - panStart.current.x),
        y: panOffsetStart.current.y + (e.clientY - panStart.current.y),
      });
    };
    const onUp = (e: PointerEvent) => {
      if (e.button !== 1) return;
      setIsPanning(false);
    };

    el.addEventListener('pointerdown', onDown);
    el.addEventListener('pointermove', onMove);
    el.addEventListener('pointerup', onUp);
    return () => {
      el.removeEventListener('pointerdown', onDown);
      el.removeEventListener('pointermove', onMove);
      el.removeEventListener('pointerup', onUp);
    };
  }, [isPanning, panOffset]);

  // Prevent default middle-click scroll behavior
  useEffect(() => {
    const el = canvasRef.current;
    if (!el) return;
    const prevent = (e: MouseEvent) => { if (e.button === 1) e.preventDefault(); };
    el.addEventListener('mousedown', prevent);
    return () => el.removeEventListener('mousedown', prevent);
  }, []);

  const resetView = () => { setCanvasZoom(1); setPanOffset({ x: 0, y: 0 }); };
  const zoomIn = () => setCanvasZoom(z => Math.min(3, z + 0.15));
  const zoomOut = () => setCanvasZoom(z => Math.max(0.1, z - 0.15));

  const selectedPage = pages.find(p => p.id === selectedPageId);
  const selectedSection = selectedPage && selectedSectionIdx !== null ? selectedPage.elements[selectedSectionIdx] : null;

  const savePageElements = async (pageId: string, elements: EditorElement[]) => {
    await supabase.from('designer_pages').update({ elements: elements as any }).eq('id', pageId);
    setPages(prev => prev.map(p => p.id === pageId ? { ...p, elements } : p));
    notifySitePagesUpdated();
  };

  const handleSectionClick = (pageId: string, sectionIdx: number) => {
    setSelectedPageId(pageId);
    setSelectedSectionIdx(sectionIdx);
    setShowAddPanel(false);
  };

  const handleMoveUp = () => {
    if (!selectedPage || selectedSectionIdx === null || selectedSectionIdx === 0) return;
    const els = [...selectedPage.elements];
    [els[selectedSectionIdx - 1], els[selectedSectionIdx]] = [els[selectedSectionIdx], els[selectedSectionIdx - 1]];
    savePageElements(selectedPage.id, els);
    setSelectedSectionIdx(selectedSectionIdx - 1);
  };

  const handleMoveDown = () => {
    if (!selectedPage || selectedSectionIdx === null || selectedSectionIdx >= selectedPage.elements.length - 1) return;
    const els = [...selectedPage.elements];
    [els[selectedSectionIdx], els[selectedSectionIdx + 1]] = [els[selectedSectionIdx + 1], els[selectedSectionIdx]];
    savePageElements(selectedPage.id, els);
    setSelectedSectionIdx(selectedSectionIdx + 1);
  };

  const handleDuplicate = () => {
    if (!selectedPage || selectedSectionIdx === null) return;
    const els = [...selectedPage.elements];
    const clone = JSON.parse(JSON.stringify(els[selectedSectionIdx]));
    const assignIds = (el: EditorElement) => { el.id = crypto.randomUUID(); el.children?.forEach(assignIds); };
    assignIds(clone);
    els.splice(selectedSectionIdx + 1, 0, clone);
    savePageElements(selectedPage.id, els);
    setSelectedSectionIdx(selectedSectionIdx + 1);
  };

  const handleDelete = () => {
    if (!selectedPage || selectedSectionIdx === null) return;
    const els = selectedPage.elements.filter((_, i) => i !== selectedSectionIdx);
    savePageElements(selectedPage.id, els);
    setSelectedSectionIdx(null);
  };

  const handleReplace = (block: SectionBlock) => {
    if (!selectedPage || selectedSectionIdx === null) return;
    const els = [...selectedPage.elements];
    const fresh = JSON.parse(JSON.stringify(block.elements[0] || block.elements));
    const assignIds = (el: EditorElement) => { el.id = crypto.randomUUID(); el.children?.forEach(assignIds); };
    if (Array.isArray(fresh)) {
      fresh.forEach(assignIds);
      els.splice(selectedSectionIdx, 1, ...fresh);
    } else {
      assignIds(fresh);
      els[selectedSectionIdx] = fresh;
    }
    savePageElements(selectedPage.id, els);
  };

  const handleAddSection = (block: SectionBlock) => {
    if (!selectedPageId) return;
    const page = pages.find(p => p.id === selectedPageId);
    if (!page) return;
    const fresh = JSON.parse(JSON.stringify(block.elements)) as EditorElement[];
    const assignIds = (el: EditorElement) => { el.id = crypto.randomUUID(); el.children?.forEach(assignIds); };
    fresh.forEach(assignIds);
    const newEls = [...page.elements, ...fresh];
    savePageElements(page.id, newEls);
    setShowAddPanel(false);
  };

  const addPage = async () => {
    if (!siteId) return;
    const { data: userData } = await supabase.auth.getUser();
    if (!userData.user) return;
    const newPage = {
      site_id: siteId,
      user_id: userData.user.id,
      page_name: `Page ${pages.length + 1}`,
      slug: `/page-${pages.length + 1}`,
      sort_order: pages.length,
    };
    const { data } = await supabase.from('designer_pages').insert(newPage).select().single();
    if (data) {
      const page = { ...data, elements: [] as EditorElement[], sort_order: data.sort_order ?? 0 };
      setPages(prev => [...prev, page]);
      setSelectedPageId(data.id);
      setShowAddPanel(true);
      notifySitePagesUpdated();
    }
  };

  const devices = [
    { key: 'desktop' as const, icon: Monitor, label: 'Desktop' },
    { key: 'tablet' as const, icon: Tablet, label: 'Tablet' },
    { key: 'mobile' as const, icon: Smartphone, label: 'Mobile' },
  ];

  const hasSitemapPages = pages.length > 0;
  const pagesAllEmpty = pages.length > 0 && pages.every(p => !p.elements || p.elements.length === 0);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full" style={{ backgroundColor: '#181818' }}>
        <div className="w-6 h-6 border-2 border-[#333] border-t-[#0073E6] rounded-full animate-spin" />
      </div>
    );
  }

  // Show building animation during auto-generation
  if (showBuildAnimation && (isAutoGenerating || pagesAllEmpty)) {
    return (
      <div className="relative h-full w-full" style={{ backgroundColor: '#141414' }}>
        <WireframeBuildingAnimation
          pageNames={pages.map(p => p.page_name)}
          progress={autoGenProgress}
          generating={isAutoGenerating}
          onComplete={() => setShowBuildAnimation(false)}
        />
      </div>
    );
  }

  // If no sitemap pages exist, show prompt to generate sitemap first
  if (!hasSitemapPages && !showAIGenerator) {
    return (
      <div className="flex items-center justify-center h-full" style={{ backgroundColor: '#181818' }}>
        <div className="flex flex-col items-center gap-4 text-center">
          <Sparkles className="h-8 w-8 text-[#333]" />
          <div>
            <p className="text-sm font-semibold text-[#666]">No sitemap generated yet</p>
            <p className="text-[11px] text-[#444] mt-1">Generate a sitemap first, then come back to generate wireframes</p>
          </div>
          <p className="text-[10px] text-[#555] px-8 max-w-sm">
            Go to the <strong className="text-[#888]">Sitemap</strong> tab and use the AI generator to create your page structure. Once your sitemap is ready, wireframes can be auto-generated from it.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-full w-full" style={{ backgroundColor: '#181818' }}>
      {/* Section editor sidebar */}
      {selectedSection && !showAddPanel && (
        <WireframeSectionEditor
          section={selectedSection}
          sectionIndex={selectedSectionIdx!}
          totalSections={selectedPage?.elements.length || 0}
          onClose={() => setSelectedSectionIdx(null)}
          onMoveUp={handleMoveUp}
          onMoveDown={handleMoveDown}
          onDuplicate={handleDuplicate}
          onDelete={handleDelete}
          onReplace={handleReplace}
        />
      )}

      {/* Add section sidebar */}
      {showAddPanel && selectedPageId && (
        <WireframeAddSectionPanel
          onAdd={handleAddSection}
          onClose={() => setShowAddPanel(false)}
        />
      )}

      {/* AI Generator sidebar */}
      {showAIGenerator && siteId && (
        <AIWireframeGenerator
          siteId={siteId}
          onGenerated={() => { setShowAIGenerator(false); loadPages(); }}
          onClose={() => setShowAIGenerator(false)}
        />
      )}

      {/* Main wireframe area */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {/* Top bar */}
        <div className="flex items-center justify-between px-6 py-3 shrink-0" style={{ borderBottom: '1px solid #252525' }}>
          <div className="flex items-center gap-1">
            {devices.map(d => {
              const Icon = d.icon;
              const active = device === d.key;
              return (
                <button
                  key={d.key}
                  onClick={() => setDevice(d.key)}
                  className="h-7 px-3 flex items-center gap-1.5 rounded-md text-[10px] font-medium transition-all"
                  style={{
                    backgroundColor: active ? '#0073E6' : '#252525',
                    color: active ? '#fff' : '#888',
                    border: `1px solid ${active ? '#0073E6' : '#333'}`,
                  }}
                >
                  <Icon className="h-3.5 w-3.5" />
                  {d.label}
                </button>
              );
            })}
          </div>

          {/* Zoom controls */}
          <div className="flex items-center gap-1">
            <button onClick={zoomOut} className="h-7 w-7 flex items-center justify-center rounded-md transition-all hover:bg-white/10" style={{ backgroundColor: '#252525', border: '1px solid #333' }}>
              <ZoomOut className="h-3.5 w-3.5 text-[#888]" />
            </button>
            <span className="text-[10px] font-mono text-[#888] w-12 text-center select-none">{Math.round(canvasZoom * 100)}%</span>
            <button onClick={zoomIn} className="h-7 w-7 flex items-center justify-center rounded-md transition-all hover:bg-white/10" style={{ backgroundColor: '#252525', border: '1px solid #333' }}>
              <ZoomIn className="h-3.5 w-3.5 text-[#888]" />
            </button>
            <button onClick={resetView} className="h-7 w-7 flex items-center justify-center rounded-md transition-all hover:bg-white/10 ml-1" style={{ backgroundColor: '#252525', border: '1px solid #333' }} title="Reset view">
              <Maximize className="h-3.5 w-3.5 text-[#888]" />
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => { setShowAIGenerator(!showAIGenerator); setShowAddPanel(false); setSelectedSectionIdx(null); }}
              className="h-7 px-3 flex items-center gap-1.5 rounded-md text-[10px] font-semibold transition-all"
              style={{
                backgroundColor: showAIGenerator ? '#a78bfa' : 'rgba(167,139,250,0.15)',
                color: showAIGenerator ? '#000' : '#a78bfa',
                border: `1px solid ${showAIGenerator ? '#a78bfa' : 'rgba(167,139,250,0.3)'}`,
              }}
            >
              <Sparkles className="h-3.5 w-3.5" />
              AI Generate Wireframes
            </button>
            <span className="text-[10px] text-[#555]">
              {pages.length} page{pages.length !== 1 ? 's' : ''} from sitemap
            </span>
          </div>
        </div>

        {/* Infinite canvas */}
        <div
          ref={canvasRef}
          className="flex-1 overflow-hidden relative"
          style={{
            cursor: isPanning ? 'grabbing' : 'default',
            backgroundColor: '#141414',
            backgroundImage: 'radial-gradient(circle, #222 1px, transparent 1px)',
            backgroundSize: `${20 * canvasZoom}px ${20 * canvasZoom}px`,
            backgroundPosition: `${panOffset.x}px ${panOffset.y}px`,
          }}
        >
          <div
            style={{
              transform: `translate(${panOffset.x}px, ${panOffset.y}px) scale(${canvasZoom})`,
              transformOrigin: '0 0',
              position: 'absolute',
              top: 0,
              left: 0,
            }}
          >
            <div className="flex gap-6 p-8 flex-wrap" style={{ minWidth: 'max-content' }}>
              {pages.map(page => (
                <div key={page.id} className="flex flex-col items-center gap-2">
                  <span className="text-[10px] font-semibold text-[#888] uppercase tracking-wider whitespace-nowrap">{page.page_name}</span>
                  <div
                    className="rounded-lg overflow-hidden transition-all"
                    style={{
                      width: cardWidth,
                      border: selectedPageId === page.id ? '2px solid #0073E6' : '1px solid #333',
                      boxShadow: selectedPageId === page.id ? '0 0 20px rgba(0,115,230,0.15)' : '0 4px 16px rgba(0,0,0,0.3)',
                    }}
                  >
                    {/* Browser chrome */}
                    <div className="flex items-center gap-1.5 px-2.5 py-1.5" style={{ backgroundColor: '#252525', borderBottom: '1px solid #333' }}>
                      <div className="flex gap-1">
                        <div className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: '#ff5f57' }} />
                        <div className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: '#febc2e' }} />
                        <div className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: '#28c840' }} />
                      </div>
                      <div className="flex-1 h-3 rounded mx-3" style={{ backgroundColor: '#1e1e1e' }} />
                    </div>

                    {/* Rendered page content */}
                    {page.elements.length > 0 ? (
                      <div style={{ backgroundColor: '#1e1e1e', overflow: 'hidden', position: 'relative' }}>
                        <div
                          style={{
                            width: previewWidth,
                            transform: `scale(${scale})`,
                            transformOrigin: 'top left',
                            pointerEvents: 'none',
                            userSelect: 'none',
                          }}
                          dangerouslySetInnerHTML={{ __html: renderPageHTML(page.elements) }}
                        />
                        {/* Click overlay zones */}
                        <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column' }}>
                          {page.elements.map((el, idx) => (
                            <div
                              key={el.id || idx}
                              className="relative cursor-pointer transition-all flex-1"
                              style={{
                                outline: selectedPageId === page.id && selectedSectionIdx === idx ? '2px solid #0073E6' : 'none',
                                pointerEvents: 'auto',
                                minHeight: 12,
                              }}
                              onClick={() => handleSectionClick(page.id, idx)}
                            >
                              <div
                                className="absolute inset-0 opacity-0 hover:opacity-100 transition-opacity flex items-center justify-center"
                                style={{ backgroundColor: 'rgba(0,115,230,0.08)', border: '1px solid rgba(0,115,230,0.3)' }}
                              >
                                <span className="text-[8px] font-medium px-2 py-0.5 rounded" style={{ backgroundColor: 'rgba(0,0,0,0.7)', color: '#fff' }}>
                                  {el.name || el.type}
                                </span>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    ) : (
                      <div className="flex flex-col items-center justify-center py-12 gap-2" style={{ backgroundColor: '#1e1e1e' }}>
                        <span className="text-[10px] text-[#555]">Empty page</span>
                      </div>
                    )}

                    {/* Add section button */}
                    <button
                      onClick={() => { setSelectedPageId(page.id); setShowAddPanel(true); setSelectedSectionIdx(null); }}
                      className="w-full flex items-center justify-center gap-1.5 py-2 text-[9px] font-medium transition-colors hover:bg-white/5"
                      style={{ backgroundColor: '#1a1a1a', color: '#0073E6', borderTop: '1px solid #2a2a2a' }}
                    >
                      <Plus className="h-3 w-3" /> Add Section
                    </button>
                  </div>
                  <span className="text-[8px] text-[#444] font-mono">{page.slug}</span>
                </div>
              ))}

              {/* Add page card */}
              <div className="flex flex-col items-center gap-2">
                <span className="text-[10px] font-semibold text-transparent uppercase tracking-wider">Add</span>
                <button
                  onClick={addPage}
                  className="rounded-lg flex flex-col items-center justify-center gap-2 transition-all hover:border-[#0073E6] hover:bg-white/[0.02]"
                  style={{ width: cardWidth, minHeight: 200, border: '2px dashed #333' }}
                >
                  <Plus className="h-5 w-5 text-[#555]" />
                  <span className="text-[10px] font-medium text-[#555]">Add Page</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
